### ISSUE TITLE
Missing Eval.h

### ISSUE THREAD

**Issue by jimmyoic** [zakki/Ray#1]
Hi,
I've tried to build this project but it turns out it lost a header file "Eval.h".
I can't find it in the src/ directory, 
Do I miss something?

Thanks!

**Comment by zakki** [comment]
Rn depends on CNTK.
Install CNTK 2.0 Beta 6, and add "CNTK-2-0-beta6-0-Windows-64bit-GPU/cntk/Include/" to include path.
https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta6.0

**Comment by jimmyoic** [comment]
Hi,
I followed the suggestion but I got the following error message instead of missing header:
src/UctSearch.o: In function `ReadWeights()':.
/home/username/GO/jimmyoic/Ray/src/UctSearch.cpp:2051 undefined reference to `GetEvalF'

Thanks for the help!
Jimmy

**Comment by zakki** [comment]
I haven't compiled on linux, but maybe something like `-leval -lcntkmath`
