### ISSUE TITLE
Can you make a brief statement to the parameters of rn?

### ISSUE THREAD

**Issue by bjiyxo** [zakki/Ray#101]
resign_threshold (0.0 <= x <= 1.0)
expand_threshold (1 <= x)
c_puct (0.0 < x)
value_scale (0.0 <= x <= 1.0)
policy_temperature (0.0 <= x)
tgr1_rate (0 <= x <= 100)
lgrf1_rate (0 <= x <= 100)

Those parameters make tuning rn flexible. However, can you make a brief statement to the parameters above.(Maybe the larger will meet the horizon effect, etc.)

**Comment by zakki** [comment]
Revision of wiki or README.md are needed.
Some of parameters come from AlphaGo paper and kobanium's paper, so there are in depth discussion on these papers.

Silver, David, et al. "Mastering the game of Go with deep neural networks and tree search." Nature 529.7587 (2016): 484-489.
Yuki, Kobayashi "モンテカルロ木探索を用いた強い囲碁プログラムの設計と開発" (2015)

**Comment by zakki** [comment]
https://github.com/zakki/Ray/wiki/Parameters
