### ISSUE TITLE
Hey zakki

### ISSUE THREAD

**Issue by zakgod** [zakki/Ray#105]
U solved many around 33 corner 1 line bugs.
Ray's life and deaths dramatically improved.
You did great. I really woder how you improved it.
Still Ray does easy mistake in big life death battle.
I think it will improve soon.

**Comment by zakki** [comment]
I did nothing for that. Maybe new value network is bit wise.
Ten millions of high quality game records ~ ten thousands GPU hours ~ millions dollars are needed.
