### ISSUE TITLE
Rn won two games aginst Zen 15.3 in the CGOS

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#109]
http://www.yss-aya.com/cgos/19x19/cross/Zen-15.3-1c1g.html

Zen is strongest AI excepct for Alphago and human are no match for Zen anymore. But Rn beated Zen twice. That's the difference between proplayers and Rn. I expect that Rn will outperform proplayers soon.

**Comment by a22063821** [comment]
Requires a breakthrough algorithm

**Comment by Azirine** [comment]
What are the parameters for Rn.4.20-4c?

**Comment by a22063821** [comment]
download:https://github.com/zakki/Ray/archive/nn.zip
Need to compile

**Comment by wjx0912** [comment]
good job!
