### ISSUE TITLE
Are there updates to te model?

### ISSUE THREAD

**Issue by brynne8** [zakki/Ray#11]
I've seen changes of code from Rn 3.6 to 3.11, but the model.bin seems stable. Are there updates of the trained model?

**Comment by zakki** [comment]
3.x uses same model.
The model.bin will be stable until new idea is found.
The reinforced learning like AlphaGo is not implemented.

**Comment by zakki** [comment]
I haven't pushed 3.11 tag yet.

**Comment by brynne8** [comment]
Thank you for speedy reply.
