### ISSUE TITLE
ray sir

### ISSUE THREAD

**Issue by Alpha-gosy** [zakki/Ray#111]
Which version of the r.n is the most stronger in gtx1070 8gb i7-6600 computer? And How can I make R.n more stronger and attack  more opponet's head? And How can I receive r.n 4.20exe? There is no file in this website r.n4.20exe . But R.n 4.20 compile is exist. Can I copy 4.20compile and use gogui to 4.61exe than?

**Comment by a22063821** [comment]
no 
Please make your own compilation
