### ISSUE TITLE
Overclocking

### ISSUE THREAD

**Issue by ghost** [zakki/Ray#119]
When I overclock my graphics card, does boosting memory clock increase ray performance, or is it only core clock that matters?

**Comment by tartaric** [comment]
You meant on your CPU I suppose, because I never heard about overlock on a graphic card. To answer, it should increase ray performance because ray uses processor + graphic card and not only that last.

**Comment by zakki** [comment]
On my PC, bottleneck isn't memory. But it depends on condition. Change and see "Playout Speed".
