### ISSUE TITLE
bugs in 4.20

### ISSUE THREAD

**Issue by bjiyxo** [zakki/Ray#122]
(;GM[1]FF[4]
SZ[19]
GN[]
DT[2017-08-26]
PB[Human]
PW[Rayon]
BR[9段]
WR[9段]
KM[0]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[60]TC[3]TT[30]AP[foxwq]
;B[pd];W[dd];B[pq];W[dp];B[qk];W[nc];B[cq];W[cp];B[dq];W[fq];B[eq];W[ep];B[fr];W[qf];B[of];W[ph];B[qg];W[qh];B[md];W[pf];B[og];W[pg];B[nd];W[po];B[gq];W[fp];B[fc];W[er];B[gr];W[bq];B[dr];W[qq];B[cf];W[ef];B[cj];W[cl];B[qp];W[pp];B[rq];W[qr];B[pr];W[rp];B[qo];W[ro];B[qn];W[rr];B[pn];W[no];B[mq];W[lp];B[lq];W[on];B[om];W[nm];B[ol];W[nl];B[ok];W[kp];B[np];W[mo];B[rn];W[qd];B[qc];W[pc];B[oc];W[pb];B[qb];W[ob];B[od];W[rd];B[nb];W[ch];B[dl];W[cm];B[dg];W[di];B[eg];W[gf];B[fg];W[fd];B[gd];W[ec];B[fe];W[ff];B[dj];W[ei];B[gg];W[gi];B[ed];W[ee];B[fd];W[hf];B[dc];W[cc];B[eb];W[ce];B[bf];W[bh];B[hg];W[if];B[cb];W[ig];B[hi];W[ih];B[fj];W[ej];B[fi];W[ek];B[bd];W[be];B[cd];W[df];B[cg];W[ad];B[de];W[mb];B[mc];W[dd];B[bc];W[hj];B[de];W[hh];B[gj];W[ii];B[fl];W[na];B[nc];W[dd];B[af];W[ae];B[de];W[rb];B[pa];W[dd];B[hl];W[de];B[ho];W[gn];B[im];W[kq];B[sq];W[sr];B[qs];W[hn];B[in];W[io];B[jk];W[sp];B[rs];W[nr];B[oq];W[oo];B[mr];W[kr];B[hk];W[ik];B[il];W[ij];B[jo];W[ip];B[iq];W[jp];B[go];W[fn];B[mk];W[fh];B[gh];W[eh];B[lm];W[nk];B[nj];W[mj];B[lk];W[mi];B[ni];W[mp];B[nq];W[kj];B[ko];W[ls];B[ms];W[ps];B[jr];W[kk];B[mn];W[nn];B[kl];W[fk];B[gk];W[oj];B[nh];W[qj];B[rl];W[pk];B[pl];W[qm];B[rm];W[pj];B[rj];W[sk];B[mm];W[jl])

At move 142, Rn could move Q1 to live, but he moved T2 and died.

(;GM[1]FF[4]
SZ[19]
GN[]
DT[2017-08-23]
PB[Human]
PW[Rayon]
BR[9段]
WR[9段]
KM[0]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[300]TC[3]TT[20]AP[foxwq]
;B[pd];W[dp];B[qp];W[dd];B[oq];W[qf];B[nc];W[qo];B[po];W[qn];B[rp];W[pj];B[cf];W[fc];B[bd];W[qc];B[qd];W[rd];B[re];W[rc];B[qe];W[ob];B[nb];W[oc];B[od];W[nd];B[lc];W[pf];B[ne];W[md];B[of];W[me];B[mf];W[kd];B[kc];W[lf];B[mg];W[jd];B[jc];W[lg];B[mh];W[rf];B[se];W[na];B[mc];W[ic];B[ib];W[hc];B[ma];W[lh];B[qh];W[qi];B[rh];W[ph];B[pg];W[og];B[qg];W[oi];B[mi];W[ri];B[sg];W[li];B[oa];W[ch];B[ef];W[cc];B[de];W[eh];B[ed];W[ec];B[cd];W[cn];B[dc];W[nq];B[id];W[op];B[pq];W[np];B[pn];W[qm];B[pp];W[hb];B[iq];W[qa];B[rb];W[sb];B[ra];W[qb];B[sd];W[pc];B[pa];W[mj];B[fq];W[ni];B[ie];W[jf];B[db];W[ng];B[sf];W[jb];B[kb];W[ia];B[sc];W[sa];B[dm];W[dn];B[fm];W[eq];B[fr];W[em];B[el];W[en];B[fl];W[jq];B[jp];W[kq];B[ip];W[ck];B[cl];W[bl];B[kp];W[nn];B[mo];W[on];B[pm];W[lm];B[jm];W[go];B[di];W[hm];B[hl];W[or];B[ql];W[rl];B[pl];W[il];B[im];W[hn];B[hk];W[ik];B[lq];W[lr];B[kr];W[ij];B[bk];W[bj];B[dk];W[cj];B[bm];W[ak];B[hj];W[hi];B[gi];W[gh];B[fi];W[fh];B[ei];W[fk];B[dh];W[dg];B[hh];W[ii];B[gg];W[hg];B[ih];W[ig];B[jh];W[gf];B[ji];W[gl];B[gj];W[jr];B[mr];W[ks];B[jl];W[mq];B[cm];W[dj];B[gm];W[kn];B[dr];W[er];B[es];W[cq];B[cr];W[bq];B[io];W[fp];B[am];W[gq];B[gr];W[hq];B[ir];W[cg];B[hr];W[fs];B[gs];W[ej];B[gk];W[al];B[rk];W[sk];B[dq];W[bn];B[ep];W[an];B[dl];W[br];B[rb];W[ra];B[na];W[qr];B[pr];W[ps];B[rr];W[rs];B[rm];W[sm];B[sl];W[kj];B[jj];W[rl];B[rn];W[sn];B[sl])

At move 62, Rn didn't choose Q17 to live, and black killed white immediately.

(;GM[1]FF[4]
SZ[19]
GN[]
DT[2017-08-27]
PB[Rayon]
PW[Human]
BR[9段]
WR[9段]
KM[0]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[W+R]TM[60]TC[3]TT[15]AP[foxwq]
;B[pd];W[dd];B[qp];W[dq];B[do];W[co];B[dp];W[cp];B[eq];W[dr];B[dn];W[cn];B[dm];W[cm];B[er];W[dl];B[el];W[kp];B[mq];W[hp];B[lo];W[fp];B[dk];W[cl];B[ep];W[ek];B[fl];W[fn];B[ej];W[jn];B[fk];W[oq];B[op];W[pp];B[po];W[pq];B[qq];W[np];B[oo];W[nq];B[ko];W[jo];B[kq];W[qr];B[rr];W[no];B[jp];W[ip];B[jq];W[qo];B[ro];W[qn];B[pm];W[rn];B[pr];W[nm];B[om];W[ql];B[pk];W[mr];B[lm];W[lr];B[lq];W[mm];B[or];W[nr];B[nk];W[rp];B[rq];W[so];B[ll];W[qs];B[rs];W[sq];B[im];W[hn];B[cq];W[cr];B[bq];W[br];B[ir];W[jl];B[jm];W[kn];B[ln];W[km];B[kl];W[hl];B[il];W[ik];B[jk];W[hm];B[hk];W[go];B[gq];W[ij];B[hj];W[in];B[jl];W[gl];B[fm];W[gm];B[fo];W[eo];B[en];W[fo];B[fc];W[ic];B[ld];W[cf];B[db];W[cc];B[fe];W[gd];B[fd];W[gc];B[ge];W[fb];B[hd];W[gb];B[dc];W[ec];B[cd];W[eb];B[id];W[jc];B[jd];W[de];B[qi];W[qc];B[qd];W[pc];B[oc];W[ob];B[nc];W[nb];B[rc];W[rb];B[rd];W[mc];B[md];W[lc];B[qb];W[pb];B[dg];W[ef];B[df];W[ee];B[fg];W[eg];B[cg];W[eh];B[fh];W[rj];B[qm];W[rm];B[rk];W[qk];B[qj];W[rl];B[nn];W[pl];B[ol];W[mn];B[on];W[mo];B[bd];W[bc];B[bb];W[cb];B[ac];W[da];B[ce];W[ri];B[qh];W[pj];B[ps];W[sr];B[kr];W[ns];B[ml];W[os];B[mp];W[qs];B[qr];W[sp];B[nl];W[ss];B[bf];W[rh];B[qg];W[ok];B[oi];W[pi];B[oh];W[kd];B[ke];W[kc];B[ff];W[rg];B[rf];W[bj];B[bi];W[ci];B[bh];W[qf];B[pf];W[sf];B[qe];W[ds];B[bk];W[ck];B[aj];W[cj];B[sb];W[ra];B[bl];W[bm];B[ak];W[ei];B[fi];W[ab];B[aa];W[es];B[ad];W[se];B[oj];W[gr];B[fq];W[dj];B[pk];W[nd];B[od];W[ok];B[am];W[an];B[pk];W[ai];B[ah];W[ok];B[fs];W[fr];B[pk];W[gk];B[gj];W[ok];B[hr];W[gs];B[pk];W[le];B[me];W[ok];B[bs];W[aq];B[pk];W[ek];B[fj];W[ok];B[hs];W[fs];B[pk];W[je];B[lf];W[ok];B[qa];W[pa];B[pk];W[kf];B[le];W[ok];B[bp];W[bo];B[pk];W[he];B[ie];W[ok];B[ar];W[ap])

At move 71, rn didn't live at R1, and white killed black immediately.

Please fix those bugs. Thank you.

**Comment by zakki** [comment]
Do you have any idea about how to solve that?

**Comment by a22063821** [comment]
## Your first sgf
10 seconds or 1 second thinking, RN move T2 

## Your second sgf
My Rn spent 0.847 seconds down to the Q17 you said
![8888](https://user-images.githubusercontent.com/29286226/29781462-d7d6c354-8c4b-11e7-8d7e-dcb4aacdcb56.png)

## Your third sgf

Think time 10 seconds Rn will have this choice of R1

**So only the first SGF has a problem**

**Comment by bjiyxo** [comment]
These sgf are tested under Dual E5-2696v2(only use 24 threads) and Dual GTX 1080Ti.


> Your second sgf
> My Rn spent 0.847 seconds down to the Q17 you said

Rn will choose Q17 at the first glance, but when rn thinks longer, he sometimes will choose M11 and wish black to choose N10. It depends.


> Your third sgf
> Think time 10 seconds Rn will have this choice of R1

Rn will never choose R1 in my hardware.


> Do you have any idea about how to solve that?

I'm not a go programmer, so I can only give the pro go advice.
First, I think the first and third sgf are the same bug. That is a really common Tesuji(手筋) "First Line Sagari"(一路立). Take the first sgf for example, the most important thing is that whether Q1 is a forcing move. If not, then it will die.  Maybe you can add some pattern recognition to solve this kind of bug.
Second, the opponent rn all know how to kill it in these cases. Maybe you add something that whether the opponent rn is going to nearly 100% kill my dragon. If yes, then the most important thing is protect my dragon.
