### ISSUE TITLE
About train question

### ISSUE THREAD

**Issue by zakgod** [zakki/Ray#125]
For train, when I create data.txt and then run Cntk 
'Total numbers of elements does not match' error message occurs.
Question 1 How do I configure data.txt?
Question2  Which model should I use in config folder?
I used cntk2.1
Sorry for silly question.
I need your help.thank you.

**Comment by zakki** [comment]
`model3.bin` is createded by ResNetV97.bs and ResNetV97_1.bs. It uses data.txt that is generated by exp-gnugo-value branch.
I used CNTK-2-0-beta12-0 to train.

**Comment by zakgod** [comment]
Really thx

**Comment by zakki** [comment]
I added Version section. https://github.com/zakki/Ray/wiki/Train

**Comment by zakgod** [comment]
Finally It works .thanks. but I used small test data files. Now I should test full files.^^

**Comment by zakgod** [comment]
For ray's self game random moves, what is useful?
I will try to make ray's self random game moves.
Is it effective to configure value_scale 0?

**Comment by zakki** [comment]
I'm trying like this. https://github.com/zakki/Ray/commit/b718194d34952910c4aca67dddb73b8cba9066fb
But it's too slow to generate 1000000 games.

Reinforcement learning policy network like AlphaGo,  enormous computing resource, or some other hack is needed.

**Comment by zakgod** [comment]
Sorry for continuos question. Does newest version rn use all model.bin(1,2,3)? Or just use model2.bin?
And for using rn4.20 version train,  should I train  all model.bin(1,2,3)? or just model2.bin?

**Comment by zakki** [comment]
4.20 uses 2 and 3. https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L2379

**Comment by zakgod** [comment]
Thank you sir~

**Comment by zakgod** [comment]
Question 1 . You trained about 700times with datasets. The more I train the better? Or is over 700 times is best?
Question 2 . I didn compiled generate kifu3 branch yet. Maybe I will try it in cloud. Can u explain how to use generate kifu3 branch? should I set total number of games? Does this make just sgf files or gtp files continuously? Does this make auto saved directory etc?

**Comment by zakki** [comment]
A1. It depends on a dataset, model, learning rate etc. So try and error.
A2. It outputs SGF as GTP responce. It's experimental and under development. So use it to read source code.

**Comment by zakgod** [comment]
Sorry zakki for continuos question.
After train model2  value is ok.
But after train model3 value network value is always between 49~50. Each move very small changing value score. I used rn 4.20.4 .
What's the problem?
What is my mistake?
When I used trained model2.bin + original model3.bin value score works well.
But when using trained model3.bin,value score is odd.

**Comment by zakgod** [comment]
For model2 train I used nn branch. For model3 train I used gnugo branch.

**Comment by zakki** [comment]
CNTK log may know. If a training error is far smaller than a cross validation error, it's over fitting.

**Comment by zakgod** [comment]
Thx you are too kind~

**Comment by trainewbie** [comment]
What does it mean? -> Run ray with converted gtp file to generate 'data.txt.
Upper line is very simple, but I couldn't generate data.txt from converted gtp files.
Is there a hidden ray command or gtp command?

**Comment by zakki** [comment]
> What does it mean? -> Run ray with converted gtp file to generate 'data.txt.

 for example.
`$ cat foo/bar.gtp | ray --no-nn --thread 4`

> gtp command

`_store`, `_dump` and `_clear`.

**Comment by trainewbie** [comment]
Thank you so much. I generated data.txt

**Comment by zakgod** [comment]
--no-nn ? Your script doesnt have --no-nn command.
Is it necessary --no-nn command to creat data.txt?

**Comment by zakki** [comment]
There is no such option in 6 Jan. It has no harm except long startup time, but also few merit.

**Comment by zakgod** [comment]
Sorry for continuous question.
Question 1. When training I understand additional training, but I just want check again.

When I train, does Rn's original model data disappear? Or does new train data is added to Ray's original model data?

Question 2. whenever I  train, should I use  previous traind kifu files plus addtional kifu files? Or is it enough to use only additional kifu files?

**Comment by zakki** [comment]
You may use `BS.Network.Load` to use other model, also you can create new model from scratch.
Both of your questions depends on what you want and what you write to .cntk and .bs.

**Comment by zakgod** [comment]
Thx zakki

**Comment by zakgod** [comment]
Hm..when i create data.txt from gtp, Ray use only one core even if  I give thread command. I don know why.
It takes too much time to create data.txt.
Is it normal to use only one core?

**Comment by zakki** [comment]
I use multiple process in different folders, and that is enough for me.

**Comment by zakgod** [comment]
Ahh thx ^^
