### ISSUE TITLE
po speed slow down dramatically on multi gpu

### ISSUE THREAD

**Issue by bjiyxo** [zakki/Ray#128]
This sgf is tested under Dual E5-2696v4(only use 24 threads) and Dual 1080Ti.

(;GM[1]FF[4]
SZ[19]
GN[]
DT[2017-09-09]
PB[Human]
PW[Rn]
BR[9段]
WR[9段]
KM[0]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[60]TC[3]TT[30]AP[foxwq]
;B[pd];W[dp];B[pq];W[dd];B[fq];W[cn];B[jp];W[qn];B[po];W[rp];B[pn];W[qm];B[pk];W[pm];B[om];W[qq];B[qr];W[ol];B[pl];W[ok];B[pj];W[oj];B[pi];W[oi];B[qp];W[rq];B[oh];W[ph];B[qh];W[pg];B[og];W[qg];B[rh];W[qe];B[pe];W[rg];B[pf];W[qd];B[qc];W[rj];B[qf];W[rf];B[sg];W[nm];B[on];W[qo];B[pp];W[or];B[pr];W[nn];B[mp];W[np];B[nq];W[mq];B[no];W[mo];B[op];W[lp];B[nl];W[re];B[se];W[nh];B[ni];W[rc];B[sf];W[rd];B[nk];W[of];B[nj];W[ng];B[oi];W[pc];B[oc];W[qb];B[pb];W[qi];B[rl];W[so];B[qc];W[hq];B[jr];W[io];B[jo];W[jn];B[kn];W[in];B[km];W[ko];B[kp];W[ip];B[lo];W[pc];B[do];W[co];B[qc];W[dq];B[rb];W[pc];B[qa];W[ri];B[qc];W[jd];B[hd];W[fc];B[je];W[hc];B[kd];W[id];B[ie];W[he];B[gd];W[ge];B[kc];W[jb];B[fd];W[gc];B[fe];W[ff];B[ee];W[eg];B[de];W[ce];B[cd];W[cc];B[bd];W[cf];B[dc];W[ec];B[ed];W[db];B[kb];W[jc];B[cb];W[dd];B[gf];W[hf];B[dc];W[bc];B[bb];W[dd];B[gg];W[jf];B[if];W[hg];B[ig];W[hh];B[dc];W[ke];B[ac];W[ih];B[jg];W[jh];B[kg];W[kh];B[lg];W[lh];B[ci];W[dj];B[hr];W[gr];B[iq];W[hs];B[cj];W[ir];B[dk];W[ek];B[ej])

Rn is white and the po speed is usually greater than 20k/s. However, from move 134 to 166, rn's po speed dramatically slow down to 6k/s. I tested on one gpu rn too, and the po speed is about 10k/s and will not change in every case. Do you know why it will happen?

PS: The GPU & CPU utilization will also slow down under this case. The GPU utilization is usually about 70%, but when po slows down, it will be about 40%.

**Comment by zakki** [comment]
I don't have multi GPU PC. Developer or new PC is needed.

**Comment by zakki** [comment]
BTW, is log in stderr console available?
And what happen without `--pondering` nor `--reuse-subtree`?

**Comment by bjiyxo** [comment]
I tested without without --pondering nor --reuse-subtree. Neither of them affects po.
I don't know how to check log in stderr console.

**Comment by zakki** [comment]
CNTK doesn't support multi GPUs, so I removed multi GPU support.
