### ISSUE TITLE
about nn-v5

### ISSUE THREAD

**Issue by af990m** [zakki/Ray#132]
In the ReadWeights() function，  there is "wchar_t name[MAX_PATH];"
On Win32, there is the MAX_PATH define，but on linxu it maybe PATH_MAX.
So,it will be reported wrong when you compile it on linux.

**Comment by zakki** [comment]
Does reverting https://github.com/zakki/Ray/commit/18d88920e482d0c5cf404f7ccb98ad8074a75613 work well?

**Comment by af990m** [comment]
When I went back to the version [18d8892](https://github.com/zakki/Ray/commit/18d88920e482d0c5cf404f7ccb98ad8074a75613) , everything was fine

**Comment by af990m** [comment]
Do you think it is appropriate for me to do like this(in fornt of the UctSearch.cpp)?
```
#if defined (_WIN32)
...
#else
...
#define MAX_PATH 4096
#endif
```
