### ISSUE TITLE
Compiling Error:  #include <codecvt>

### ISSUE THREAD

**Issue by as0770** [zakki/Ray#134]
WIth g++-4.9 I get this error message:

src/UctSearch.cpp:18:19: fatal error: codecvt: Not found
 #include <codecvt>
                   ^
compilation terminated.

With another compiler I get cntk errors..

Any ideas?

Thanks in advance.

**Comment by zakki** [comment]
Current HEAD doesn't use codecvt.

**Comment by as0770** [comment]
It is the latest release. With the current version I get another error (after upgrading cudnn):

`/usr/bin/ld: warning: libCntk.PerformanceProfiler-2.1.so, needed by /usr/local/cntk/cntk/lib/libCntk.Math-2.1.so, not found`

And:

`/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ProfilerTimeEnd(long long, int)'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ProfilerInit(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, unsigned long long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, bool)'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ProfilerTimeBegin()'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ProfilerClose()'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ProfilerEnable(bool)'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ScopeProfile::ScopeProfile(int)'
/usr/local/cntk/cntk/lib/libCntk.Core-2.1.so: Nicht definierter Verweis auf `Microsoft::MSR::CNTK::ScopeProfile::~ScopeProfile()'
collect2: error: ld returned 1 exit status
`
"libCntk.PerformanceProfiler-2.1.so" is in .../cntk/cntk/lib

**Comment by zakki** [comment]
g++4.8 was ok. both g++4.8.4 and CNTK 2.1 on Ubuntu 14.04.5 LTS and g++4.8.5 and CNTK 2.2 on Deep Learning AMI CUDA 9 Amazon Linux Version.
