### ISSUE TITLE
Ray crashed with ucrtbase.dll 10.0.16299.15 in windows 10.0.16299

### ISSUE THREAD

**Issue by michaelnix** [zakki/Ray#135]
When I run ray.exe in windows 10.0.16299, it showed Init CNTK and then crashed. I find the error message:
Faulting application name: ray.exe, version: 0.0.0.0, time stamp: 0x5997e173
Faulting module name: ucrtbase.dll, version: 10.0.16299.15, time stamp: 0x70f70cc4
Exception code: 0xc0000409
Fault offset: 0x000000000006b70e
Faulting process id: 0x1824
Faulting application start time: 0x01d36101850053de
Faulting application path: C:\ray\ray.exe
Faulting module path:  C:\Windows\System32\ucrtbase.dll

how to fix it ?

**Comment by zakki** [comment]
It seems like a buffer overrun error. Since buffer size is hard coded, error may occur in deep dicetory. https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L2420

But it won't occur in c:\ray, I don't have idea.

**Comment by michaelnix** [comment]
yes , it works in c:\ray\ray.exe. oops.
