### ISSUE TITLE
Ubuntu 17.10 Compile

### ISSUE THREAD

**Issue by Philip2010** [zakki/Ray#138]
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Command.cpp -o src/Command.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/DynamicKomi.cpp -o src/DynamicKomi.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/GoBoard.cpp -o src/GoBoard.o
src/GoBoard.cpp: In function ‘void WritePlanes(std::vector<float>&, std::vector<float>&, std::vector<float>&, std::vector<float>*, const game_info_t*, const uct_node_t*, int, int)’:
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2010:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ OUTPUT_FEATURE(data_basic, color == S_BLACK); });
     ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2011:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ OUTPUT_FEATURE(data_basic, true); });
     ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2013:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ OUTPUT_FEATURE(data_basic, p == koT); });
     ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2018:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ OUTPUT_FEATURE(data_basic, ladder[0][p]); });
     ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2019:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ OUTPUT_FEATURE(data_basic, ladder[1][p]); });
     ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2023:7: note: in expansion of macro ‘OUTPUT’
       OUTPUT({
       ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2030:7: note: in expansion of macro ‘OUTPUT’
       OUTPUT({
       ^~~~~~
src/GoBoard.cpp:2000:9: warning: unused variable ‘c’ [-Wunused-variable]
     int c = game->board[p]; \
         ^
src/GoBoard.cpp:2049:5: note: in expansion of macro ‘OUTPUT’
     OUTPUT({ data_move.push_back(0.0); });
     ^~~~~~
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Gtp.cpp -o src/Gtp.o
src/Gtp.cpp: In function ‘void GTP_ray_best_sequence()’:
src/Gtp.cpp:830:7: warning: variable ‘point’ set but not used [-Wunused-but-set-variable]
   int point = PASS;
       ^~~~~
src/Gtp.cpp: In function ‘void GTP_ray_stat()’:
src/Gtp.cpp:930:7: warning: variable ‘point’ set but not used [-Wunused-but-set-variable]
   int point = PASS;
       ^~~~~
src/Gtp.cpp: In function ‘void DumpSparse(std::ostream&, std::vector<float>)’:
src/Gtp.cpp:1024:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < data.size(); i++) {
                    ~~^~~~~~~~~~~~~
src/Gtp.cpp: In function ‘void DumpDense(std::ostream&, std::vector<float>)’:
src/Gtp.cpp:1034:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < data.size(); i++) {
                    ~~^~~~~~~~~~~~~
src/Gtp.cpp: In function ‘void GTP_stat_po()’:
src/Gtp.cpp:1258:7: warning: unused variable ‘pos’ [-Wunused-variable]
   int pos = -1;
       ^~~
src/Gtp.cpp:1259:7: warning: variable ‘pass_count’ set but not used [-Wunused-but-set-variable]
   int pass_count;
       ^~~~~~~~~~
src/Gtp.cpp: At global scope:
src/Gtp.cpp:1119:1: warning: ‘void GTP_stat()’ defined but not used [-Wunused-function]
 GTP_stat(void)
 ^~~~~~~~
src/Gtp.cpp:966:12: warning: ‘features_turn_next’ defined but not used [-Wunused-variable]
 static int features_turn_next = 1;
            ^~~~~~~~~~~~~~~~~~
src/Gtp.cpp:965:12: warning: ‘features_turn_count’ defined but not used [-Wunused-variable]
 static int features_turn_count = 0;
            ^~~~~~~~~~~~~~~~~~~
src/Gtp.cpp:133:14: warning: ‘next_token’ defined but not used [-Wunused-variable]
 static char *next_token;
              ^~~~~~~~~~
src/Gtp.cpp: In function ‘void GTP_getkomi()’:
src/Gtp.cpp:493:1: warning: ‘%lf’ directive output truncated writing between 8 and 317 bytes into a region of size 4 [-Wformat-truncation=]
 GTP_getkomi( void )
 ^~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from src/Gtp.cpp:1:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 9 and 318 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Ladder.cpp -o src/Ladder.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Message.cpp -o src/Message.o
src/Message.cpp: In function ‘void PrintBestSequence(std::ostream&, const game_info_t*, const uct_node_t*, int)’:
src/Message.cpp:569:8: warning: unused variable ‘statistic’ [-Wunused-variable]
   auto statistic = root->statistic;
        ^~~~~~~~~
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/MoveCache.cpp -o src/MoveCache.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Nakade.cpp -o src/Nakade.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Pattern.cpp -o src/Pattern.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/PatternHash.cpp -o src/PatternHash.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Point.cpp -o src/Point.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Rating.cpp -o src/Rating.o
src/Rating.cpp: In function ‘int RatingMove(game_info_t*, int, std::mt19937_64*, LGR&)’:
src/Rating.cpp:293:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < tgr1_rate && game->moves > 0) {
         ~~~~~~~~~~~~~~~~^~~~~~~~~~~
src/Rating.cpp:310:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (((*mt)() % 100) < lgrf1_rate && game->moves > 0) {
         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/RayMain.cpp -o src/RayMain.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Seki.cpp -o src/Seki.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Semeai.cpp -o src/Semeai.o
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Simulation.cpp -o src/Simulation.o
src/Simulation.cpp: In function ‘int SimulationGenmove(game_info_t*, int)’:
src/Simulation.cpp:66:7: warning: unused variable ‘pos’ [-Wunused-variable]
   int pos = -1;
       ^~~
src/Simulation.cpp:68:7: warning: variable ‘pass_count’ set but not used [-Wunused-but-set-variable]
   int pass_count;
       ^~~~~~~~~~
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/UctRating.cpp -o src/UctRating.o
src/UctRating.cpp:81:15: warning: ‘criticality_init’ defined but not used [-Wunused-variable]
 static double criticality_init = CRITICALITY_INIT;
               ^~~~~~~~~~~~~~~~
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/UctSearch.cpp -o src/UctSearch.o
src/UctSearch.cpp:44:10: fatal error: CNTKLibrary.h: 没有那个文件或目录
 #include "CNTKLibrary.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:26: recipe for target 'src/UctSearch.o' failed
make: *** [src/UctSearch.o] Error 1

**Comment by zakki** [comment]
Install CNTK and set CNTKDIR in Makefile.
