### ISSUE TITLE
When generating kifu, termination bug still exists.

### ISSUE THREAD

**Issue by trainewbie** [zakki/Ray#139]
HI, zakki. I have some questions.

1. A freezing bug was solved since the last patch,
but the generation was terminated when the number of times was less than the set number of times.
When I am doing other work,  I often set over 1000~2000(with head option) times for generaing kifu. But sometimes, the actual number of generated kifu is randomly too small number.
 It is not always the case.
I guess that some micro-delay option is needed between game creation. Of course, I'm not sure.
Can you solve it?

2. Is 4k playouts still optimal option for the generated kifu?

3. Why doesn't Ray start training on the zero-base like Alphago Zero?

Regards.

**Comment by Brandonnogithub** [comment]
Hello, what is generated kifu..?

**Comment by zakki** [comment]
1. I'll look into it later.
2. Rn.4.30-4c and Rn.4.32-4c is almost same rating, and it show that 4k po self play game isn't harmful.
Rn.4.30-4c uses model6.bin that is trained by tygem, aya and Rn's self played games.
Rn.4.32-4c which uses model2.bin and model3.bin, they are trained by tygem games only.
More playout and more games are better, I don't know which is optimal.
3. AGZ requires enormous computing resource, and I don't have $1000000.
New voluntary computing project will steal Leela Zero and him each other.

> what is generated kifu..?

100k or more self play games are needed to train more strong policy network and value network.
https://github.com/zakki/Ray/tree/generate-kifu5
