### ISSUE TITLE
Will you release new rn supporting multi GPUs?

### ISSUE THREAD

**Issue by bjiyxo** [zakki/Ray#140]
As title.  Will you release new rn supporting multi GPUs if rn makes great progress?

**Comment by zakki** [comment]
Nightly build is available.
1.0.15 (~ 4.20) on release page, or 1.0.28 (~ 4.30) 
 https://ci.appveyor.com/project/zakki/ray/build/1.0.28/artifacts

**Comment by bjiyxo** [comment]
Do 1.0.28 support the model6.bin? Or is it slightly newer or older?

**Comment by zakki** [comment]
It uses model6.bin for 19x19, and model6_9.bin for 9x9.
According to tests on CGOS, it's slightly weaker than 4.20(model2 + mobel3).
