### ISSUE TITLE
What's wrong with it? the device ID

### ISSUE THREAD

**Issue by Brandonnogithub** [zakki/Ray#142]
Init CNTK
ok
play b q4
= 

play w q16
= 

genmove b
Time Limit    : 5 Sec
Playout Limit : 100000000 PO
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::invalid_argument>'
  what():  Specified GPU device id (4294967295) is invalid.
Aborted (core dumped)

this is the command:
./ray --playout 3000 --time 1800 --const-time 5 --no-gpu

**Comment by zakki** [comment]
There was --no-gpu bug, and it's fixed 147ccbe.

**Comment by zakki** [comment]
BTW, is #141 solved?

**Comment by Brandonnogithub** [comment]
Yes, #141 is my problem, I forget to delete the old .o file.
Thanks, this solutions works!

**Comment by Brandonnogithub** [comment]
Can you help me with the #143 , I don't add --no-gpu, then it doesn't work
