### ISSUE TITLE
Did it need opencl?

### ISSUE THREAD

**Issue by Arthur-Null** [zakki/Ray#145]
g++-5 -O3 -Wall -std=c++11 -std=c++1y   -I /home/hal/cntk/Include/ -D _GLIBCXX_USE_CXX11_ABI=0 -o ray src/Command.o src/DynamicKomi.o src/GoBoard.o src/Gtp.o src/Ladder.o src/Message.o src/MoveCache.o src/Nakade.o src/Pattern.o src/PatternHash.o src/Point.o src/Rating.o src/RayMain.o src/Seki.o src/Semeai.o src/Simulation.o src/UctRating.o src/UctSearch.o src/Utility.o src/ZobristHash.o -lm -pthread -L /home/hal/cntk/cntk/lib -L /home/hal/cntk/cntk/dependencies/lib -lCntk.Eval-2.1
/home/hal/openmpi/lib/libopen-pal.so.13: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/home/hal/openmpi/lib/libopen-pal.so.13: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/home/hal/openmpi/lib/libopen-pal.so.13: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
/home/hal/openmpi/lib/libopen-pal.so.13: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
collect2: error: ld returned 1 exit status
make: *** [ray] Error 1

**Comment by zakki** [comment]
Ray and CNTK doesn't require OpenCL, but your libopen-pal.so.13 seems to require it.

**Comment by Brandonnogithub** [comment]
OK, it solved. just recompile the openmpi with disable opencl
