### ISSUE TITLE
Selected CPU as the process wide default device.

### ISSUE THREAD

**Issue by Brandonnogithub** [zakki/Ray#146]
./ray --playout 3000 --time 1800 --const-time 5
Init CNTK
Selected CPU as the process wide default device.
ok

How to let it select a gpu?

**Comment by zakki** [comment]
As far as I know, fastest GPU is selected as a default device.
But you can use GPU 0 like `ray --device-id 0`.

Is CNTK "CNTK for Linux GPU" or "CNTK for Linux GPU with 1bit-SGD"?
"CNTK for Linux CPU only" can't use GPU.

**Comment by Brandonnogithub** [comment]
because my cuda is 7.5, the cntk can't find gpu
