### ISSUE TITLE
Exception occured RN-4.32

### ISSUE THREAD

**Issue by jungsup824** [zakki/Ray#153]
![rn exception occurred](https://user-images.githubusercontent.com/34597284/36639601-d9811de8-1a4a-11e8-95bb-b1d7b71cc1e9.png)
I do not know anything about Visual studio or Linux. I have downloaded RN-4.32 to play go in the internet. It was not easy for me to even successfully install CNTK. Even I installed CNTK GPU successfully, ray.exe is still not working. I do not know what's the meaning of the error. Could anybody explain me how to fix it. Pls explain detailed way for non-professional.

**Comment by zakki** [comment]
Try `ray` or `ray --no-gpu`. If they works, additional `--thread 4` or something like that will be useful.
`CNTK` command is for developer to train network.
