### ISSUE TITLE
leelazeroのnetwork weightsに関して

### ISSUE THREAD

**Issue by igofun** [zakki/Ray#155]
leelazeroのnetwork weightsファイルをこちらのRNに使う方法を教えて下さい

**Comment by zakki** [comment]
そういうパッチを書いてください。leelazeroの特徴量抽出とNN評価をUctSearch.cppにマージする形になるかと思います。

**Comment by igofun** [comment]
簡単にはできないんですね
難しそうなので諦めます
ありがとうございました
