### ISSUE TITLE
Help Needed. What should I do if I see Eval QUEUE FULL?

### ISSUE THREAD

**Issue by pcengine** [zakki/Ray#158]
Hi,  I run RN on sabaki.  But when I play RN using 30 seconds per move, it always gives Eval QUEUE FULL message. What Should I do? Please help, thank you.

**Comment by zakki** [comment]
Ignore it, or upgrade GPU. That message means tree search on CPU stalled to wait NN evaluation on GPU.

**Comment by pcengine** [comment]
Ok, thank you. I already use a 1080Ti.
Seems I need to buy a Titan V. :-)

Kensuke Matsuzaki <notifications@github.com> 於 2018年5月6日 週日 下午1:18 寫道：

**Comment by zakki** [comment]
If you use 4 ~ 10 core cpu and 1080Ti, just ignore that message.
Current Rn doesn't use TensorCore, since it don't use fp16. So perhaps Titan V may not improve performance drastically.
