### ISSUE TITLE
Add ladder detection with OpenGo ELF

### ISSUE THREAD

**Issue by jillybob** [zakki/Ray#161]
One major issue with OpenGo ELF is the lack of ladder detection at low playouts. Please include a hard-coded ladder detection feature. 

From Aq
https://github.com/ymgaq/AQ/blob/master/src/ladder.cpp
https://github.com/ymgaq/AQ/blob/master/src/ladder.h

**Comment by zakki** [comment]
Ray has ladder detection.

**Comment by jillybob** [comment]
Thanks for that, I did not know this.
