### ISSUE TITLE
Not seeing ladders

### ISSUE THREAD

**Issue by croosn** [zakki/Ray#163]
So I tried this specific position on 60 seconds and 5000 playouts, but Ray(LZ-Elf) still plays ladder even though it's hardcorded not to.
What's going on, and how many playouts does it need to see laders?

![60sec](https://user-images.githubusercontent.com/38720539/39858938-68497936-5438-11e8-94b3-6ad98a5e2ef2.png)

Edit: is it possible to do full-tuning on ray.exe?

**Comment by zakki** [comment]
It ignores one stone ( https://github.com/zakki/Ray/blob/lz/src/Ladder.cpp#L29) and short ladder (https://github.com/zakki/Ray/blob/lz/src/Ladder.cpp#L69), since it may (and also may not) be good move.
I think that is why the best sequence doesn't have "w N5".

**Comment by croosn** [comment]
I tested again with longer time settings (because of my weak gpu), and it sees that n4 is a bad move and chooses something else. Even earlier in joseki.
