### ISSUE TITLE
the winrate of rlo 0.2 over 0.1?

### ISSUE THREAD

**Issue by l1t1** [zakki/Ray#165]
http://www.yss-aya.com/cgos/19x19/cross/RLO.0.2-4c1g.html
http://www.yss-aya.com/cgos/19x19/cross/RLO.0.1-4c1g.html
from above links, it shows 0.2 can beat lz elf , is it benefit of rlo's improvement?

**Comment by l1t1** [comment]
btw could you supply a windows exe version of 0.2?

**Comment by zakki** [comment]
rlo.0.2 may be robuster than lz in ladder, some kind of capturing race and handicap game.
But as far as I tested on i7-6700K and TITAN-X, lz-elf is bit stronger in 5 seconds per move
Perhaps LZ_62b541_ELF_1600 uses 1600 playouts per move, but LZ can use 2000 or near 3000 playouts per move on my PC using 15 minutes per side game.

**Comment by l1t1** [comment]
glad to see windows version is available
https://github.com/zakki/Ray/releases/download/rlo-0.2.1/Rn.zip
