### ISSUE TITLE
rn-5.5.1 can't run in Win 7

### ISSUE THREAD

**Issue by jun63cn** [zakki/Ray#167]
Init  CNTK
Selected GPU[0] geforce gtx 1060 3gb as the process wide default device .
then crashed

**Comment by zakki** [comment]
It's 9x9 only, try `ray --size 9`.
(5.5.1 is weaker than 4.x at 19x19 board, so no weight file for 19x19 is released.)

**Comment by jun63cn** [comment]
OK got it Thanks!
