### ISSUE TITLE
Rn 5.5 issue

### ISSUE THREAD

**Issue by Climu1d** [zakki/Ray#170]
So I downloaded it, unzipped it into another folder and di literally everything the same as 4.2, but it does literally nothing on sabaki, i went to manage engines, clicked folder all the way to ray.exe and put the augments the same as 4.2, and I also tried with augment and it just has my mouse loading and nothing happens.... why isnt rn 5.5 working????

**Comment by zakki** [comment]
5.5.1 is 9x9 monumental version for CGF Open 2018.
`ray --size 9` works, but `ray --size 19` doesn't work.

There is no 19x19 weight for 5.5, because rlo-0.2.1 or rn-4.32 play much better 19x19 game than 5.5.
