### ISSUE TITLE
Congratulations RN win the runner on AI Ryusei 2018

### ISSUE THREAD

**Issue by l1t1** [zakki/Ray#171]
will you open the version used in the Competition?

**Comment by zakki** [comment]
Ryusei 2018 Rn is new RLO.
It runs on AWS EC2 p3.8xlarge, and it uses LZ's 53f805d1a0e9b2acbfbeddb9715f3c5db0581cf36aeef7c28b69c1b5dd36df32.gz 
https://github.com/zakki/Ray/commits/lz-ryusei2018

- Props
  - Non 7.5 komi and Japanese support by random rollout. (Limited)
  - Ladder detection
  - A little good at opening and ending. 

- Cons
  - Worse middle game. LZ's value network is much better than Rn's rollout.
  - Slower on multi GPUs. I have not know why.
  - Slower on a few CPU cores.

**Comment by jillybob** [comment]
Will this be compiled to work with Windows, if not are there compile instructions for Windows?

**Comment by zakki** [comment]
CI artifact is available. https://ci.appveyor.com/project/zakki/ray/builds/21043153/artifacts
There are some bugs and workaround what is needed to fix before release. `ExtendTime() ` doesn't work now.

**Comment by cjohnchen** [comment]
How to convert lz weights to RN bin weights?

**Comment by l1t1** [comment]
ray  --weights  ..\leela15\networks\8b28fe3c8df08d879dc70cbba9a8d2d3e56f4dce6cbab2e1e289851f24044288.gz can use lz weight

**Comment by zakki** [comment]
No conversion is needed. Use ` --weights` option.
For example, `ray --weights uct_params/53f805d1a0e9b2acbfbeddb9715f3c5db0581cf36aeef7c28b69c1b5dd36df32.gz --thread --thread 4 --nn-thread 2 --reuse-subtree`

**Comment by l1t1** [comment]
http://www.yss-aya.com/cgos/19x19/cross/RLO.0.6-191-16c1g.html
http://www.yss-aya.com/cgos/19x19/cross/RLO.0.7-191-16c1g.html
is seems RLO.0.6-191-16c1g is better

**Comment by l1t1** [comment]
http://www.yss-aya.com/cgos/19x19/cross/RLO.0.8-191-16c1g.html
RLO.0.8-191-16c1g is very strong, is the hardware same as  RLO.0.6-191-16c1g?

**Comment by zakki** [comment]
Yes, both of them use 2950X and 1080Ti.

**Comment by l1t1** [comment]
is the software RLO.0.8-191-16c1g newer than build 1.0.51?

**Comment by zakki** [comment]
I dropped  f034d8c  and fixed time management.

**Comment by jillybob** [comment]
What command did you feed the engine in the competition? I'm currently using

ray.exe --thread 4 --const-time 1800 --tree-size 524288 --weights C:\Rn\network.gz

but I see you've used `nn-thread --2` in your above example, I couldn't find this command in --help or readme.

**Comment by zakki** [comment]
There is `--nn-thread`. https://github.com/zakki/Ray/blob/lz/src/Command.cpp#L31

I don't remember what tree-size I use. Perhaps I used `ray --weights uct_params/53f805d1a0e9b2acbfbeddb9715f3c5db0581cf36aeef7c28b69c1b5dd36df32.gz --reuse-subtree --pondering --time 1800 --thread 16 --nn-thread 8 --device-id 0,1,2,3 --tree-size 262144`

**Comment by l1t1** [comment]
http://www.yss-aya.com/cgos/19x19/cross/Rnz-3.2.3-1080Ti.html
is this amazing bot yours?
if yes, what is weight and parameter of it?

**Comment by zakki** [comment]
Rnz is Raynz by 3-ize. Maybe yet another Rn with ELF network implementation.

BTW, I uploaded self commentary sgf files.
http://peppermint.jp/go/ai_ryusei_01/
