### ISSUE TITLE
can't compile  lzr-komi branch

### ISSUE THREAD

**Issue by jun63cn** [zakki/Ray#173]
Gtp.obj : error LNK2001: 无法解析的外部符号 "void __cdecl WritePlanes(class std::vector<float,class std::allocator<float> > &,class std::vector<float,class std::allocator<float> > &,struct game_info_t *,struct game_info_t *,int,int)" (?WritePlanes@@YAXAEAV?$vector@MV?$allocator@M@std@@@std@@0PEAUgame_info_t@@1HH@Z)
F:\Ray-5956ee5\win\x64\Release\ray.exe : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by zakki** [comment]
It's experimental branch. `lzray.pyd`, target binary  is used to train lz's model using ray's features by tensorflow.
