### ISSUE TITLE
Linux mint installation not working

### ISSUE THREAD

**Issue by ofekih** [zakki/Ray#18]
The error I'm getting is:
`src/UctSearch.cpp:41:18: fatal error: Eval.h: No such file or directory`
 `#include "Eval.h"`

`compilation terminated.`

Any clue how I can fix this?

**Comment by zakki** [comment]
Run `source <cntk dir>/activate-cntk`, and edit Makefile file.

> CNTKDIR = /home/ubuntu/src/cntk
> CFLAGS = ${OPTIMIZE} ${WARNING} ${CPP11} ${DEBUG}  -I${CNTKDIR}/Source/Common/Include/
> LIBS = -lm -pthread  -L${CNTKDIR}/lib -leval #-static-libstdc++ -static-libgcc

I think it may better to remove default CNTKDIR setting from Makefile, and show messages to setup CNTK.

**Comment by ofekih** [comment]
source <cntk dir>/activate-cntk is giving me a permission denied, even when running with sudo.

**Comment by zakki** [comment]
Did you install CNTK?

**Comment by ofekih** [comment]
That's probably the problem, installing from microsoft now

**Comment by ofekih** [comment]
Okay, that compiles now, but now it's stuck on:
`/usr/bin/ld: cannot find -leval`
`collect2: error: ld returned 1 for exit status`
`Makefile:23: recipe for target 'ray' failed`

**Comment by ofekih** [comment]
Changed my lib dir to point to the location of lib under cntk, and now i get many undefined reference errors

**Comment by zakki** [comment]
CNTK version 2.0 Beta 12 binary distribution requires g++-4.8.
