### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by brynne8** [zakki/Ray#2]
* How is the model trained? Is there a way we train the model ourselves or improve it?
* Is there a TODO list for the project?
* Is it possible to pack it with just a few libraries and an executive for release?

**Comment by zakki** [comment]
> How is the model trained? Is there a way we train the model ourselves or improve it?
1. Convert KGS/GoGod sgf files to gtp files which interleave `features_planes_file`/`_store`/`_dump`/`_stat`.
2. Run `ray`  with converted gtp file to generate 'data.txt'.
3. Shuffle and split data.txt
4. Run `cntk`. (Model definition is https://github.com/zakki/Ray/blob/nn/cntk/ , but no .cntk config file in repository yet.

I use some ugly scripts to do these tasks. I'll try to clean up and upload them.

> Is there a TODO list for the project?

No TODO list yet.

> Is it possible to pack it with just a few libraries and an executive for release?

Perhaps most files in sim_params and uct_params can be embed into exe. But all dlls in current release zip are required by cntk.
https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows

**Comment by brynne8** [comment]
Thank you for your reply. Now I downloaded the 3.3 release version. I'll check the model configuration after you uploaded them.

**Comment by zakki** [comment]
I added utilities.

https://github.com/zakki/Ray/blob/nn/cntk/TrainValueResNetV20.cntk
https://github.com/zakki/rn-tools

**Comment by zhu-jz** [comment]
Amazing
