### ISSUE TITLE
Using too much time on a move

### ISSUE THREAD

**Issue by roy7** [zakki/Ray#21]
A fellow user of OGS has been running RayN there for a bit. He's finding that it will often use more time to think than he has actually set it to. This, of course, can cause losses due to timeouts. As a work around he has set RayN to move in 10 seconds or less per move but a minimum byoyomi period of 30 seconds.

As the game gets later, it will tend to use more time than then 10 seconds. He's seen it go over 30 seconds even 4 times in a match but thankfully no timeout losses since the matches are 5 periods of 30 seconds by default.

We also did some testing in blitz games vs other bots, and with a 1 second per move target, late game RayN might be taking 7-8 seconds per move.

**Comment by zakki** [comment]
Without GPU (or with relatively slower GPU than CPU), `--reuse-subtree` or `--pondering` cause such problems. 
This is because these options force to evaluate all policy and value in queue.

**Comment by roy7** [comment]
He's running his bot off a laptop with a mobile nvidia GPU. So not the strongest GPU. But he has found with --reuse-subtree and --pondering, Rayn is noticeably stronger, even on short time settings. But for "real" use, spending too much time thinking means losing games on timeouts. He can turn these options off to never time out, but then the bot seems to lose a lot of strength.

Is it possible the queue could be interrupted if we've run out of time and a move sent out immediately?

**Comment by zakki** [comment]
https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L2341
`(!reuse_subtree && !ponder)` do that.
If some evaluation in queues are interrupted, I need to restart some of these next time.
https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L186

BTW, gtp2ogs.js seems to send `time_left` gtp command. Is `ray --time 100` suitable?
`--time n`  enables TIME_SETTING_MODE, and only TIME_SETTING_MODE uses `time_left`.
This behavior is hard to understand, I think we need better command line option.

**Comment by roy7** [comment]
Yeah gtp2ogs supports time_setting and kgs-time_setting, and will send appropriate time_left information each move. We didn't realize Ray supported gtp time data honestly. But some option to subtract time to act as a network buffer would be nice. We can subtract it ourselves, but Leela for instance does --lagbuffer 500 if you want to subtract 5 seconds from any of the time calculations, so it always moves 5 seconds before the deadline.

So instead of --const-time 5 or whatever, we should go with --time <placeholder number> and each time we send a time_left, Ray will adjust the time left internally and move in an appropriate amount of time?

Will Ray understand things like byoyomi time periods from the time_settings command?

**Comment by zakki** [comment]
> So instead of --const-time 5 or whatever, we should go with --time and each time we send a time_left, Ray will adjust the time left internally and move in an appropriate amount of time?

Yes. But I have not tried what happen when Ray uses too much time than expected.

> Will Ray understand things like byoyomi time periods from the time_settings command?

Ray can receive `time_settings`, but it ignores arguments. And Ray doesn't understand byoyomi yet.

**Comment by roy7** [comment]
For now then would it be best to special case Ray in gtp2ogs and send a time_left with the number of seconds in the byoyomi period as if it was main time? Each move I could reset it back to 30 seconds left (or whatever) so Ray keeps moving within the period length.
