### ISSUE TITLE
Multiple copies at once

### ISSUE THREAD

**Issue by roy7** [zakki/Ray#24]
Is it a limitation of the CNTK library, or something that Ray needs to handle differently, for multiple copies to run simultaneously?

**Comment by zakki** [comment]
I want to run two Ray to test by self-play using one machine.
If I launch two Ray (or also a Ray and a LeelaGPU), one Ray works well, but another Ray stall.

I couldn't find such API in CNTK Eval library. https://github.com/Microsoft/CNTK/blob/master/Source/Common/Include/Eval.h

**Comment by roy7** [comment]
Ahh. In my case it'd be to run multiple Ray at once to play games on OGS. Someone who runs Ray there already mentioned it to me that he can only have it play one game at a time.

**Comment by roy7** [comment]
@zakki Perhaps you should post it as an issue to the CNTK github? I don't really know much about CNTK to try asking myself. But it's hard to believe there wouldn't be a way to run multiple applications that all use CNTK simultaneously on the same system.

**Comment by zakki** [comment]
I'll try to reproduce this by small simple test program.

**Comment by zakki** [comment]
@roy7 Could you try https://github.com/zakki/Ray/tree/nn-nolock-gpu ?
It works for me on Windows.

**Comment by roy7** [comment]
I've not had success trying to compile Ray on Windows in the past. What build environment/tools do you use? Perhaps I can try to duplicate your setup. Previously I was using MWIN64.

**Comment by zakki** [comment]
I'm using Visual Studio Community 2015 on Windows, and make and gcc-4.8 on Linux.
I think a29f3c6 works on Linux too.

**Comment by roy7** [comment]
I built a new linux box this week, and the GPU arrives tonight. I'll give compiling Ray a try on that as well. Some of the issues I had before I think were discussed on lifein19x19 but the workarounds were pretty easy.

**Comment by ghost** [comment]
@roy7 if you build on linux and want to use a gcc 5.1 or newer with the binaries provided by Microsoft, make sure to add `-D _GLIBCXX_USE_CXX11_ABI=0`.

@zakki I tried nn-nolock-gpu on linux and I could launch two instances (btw, `deviceId=0` was enough for that to work) but if I entered `genmove black` into both at the same time, I get the following error:

```cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=dorian-pc ; expr=err
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=dorian-pc ; expr=err```

**Comment by zakki** [comment]
@antifermion It may run out of memory. 
Does smaller batch size help? For example
```
const int policy_batch_size = 4;
const int value_batch_size = 4;
```
https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L162

https://github.com/Microsoft/CNTK/wiki/Troubleshoot-CNTK
