### ISSUE TITLE
Can you add alphago's joseki?

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#26]
as you may know, alphago showed us new lots of joseki when it played "go" at the tygem(Korea baduk site) and foxwq(China weiqi site).

and if you need records of them(60games sgf files), i can send you. 

Plus, if you need Fineart(China AI)'s game records(sgf files), either i can send them to you too.(maybe over 100games)

**Comment by zakki** [comment]
I think AlphaGo's (and FineArt's) new joseki come from their Policy ant Value Network.
Teaching joseki to DCNN needs thousands or millions of records.
As far as I know, learning joseki from small data without overfit is difficult.

**Comment by zakki** [comment]
Of cause, it would be possible to implement Pachi/Fuego style joseki database or opening book.

**Comment by j8580** [comment]
Add new traing data set.
https://github.com/yenw/computer-go-dataset
