### ISSUE TITLE
What is best value number for policy batch size and value batch size?

### ISSUE THREAD

**Issue by j8580** [zakki/Ray#27]
I have I7 6900k 16thread and GTX1080ti GPU 32G DDR4 ram.

Current value number of policy and value batch size is 16 and 64.

I heard value batch size 128 is best in performance in other Deep learning community.

If I change value number , is performance or strengh of Ray will be stronger?

and..then how will be thinking time of ray ? 

also..what is best value number in my system?

**Comment by j8580** [comment]
plus..Ray is really stong at beginning and middle,,,but Ray is really weak at endgame.
How can improve endgame of Ray? any solution?..
I think at endgame..increasing policy batch size or value batch size will be helpful.

**Comment by zakki** [comment]
If you see "EVAL QUEUE FULL" or "EMPTY QUEUE" in log, those batch size may change performance.

At endgame, value network has a error due to both it's architecture and training data set.

Ray's simulation sometimes can't play well semeai, falsy eye and life and death,  these would happen at all time of game, but they are critical at endgame.

**Comment by j8580** [comment]
I got error 'eval queue full' when I changed batch size.
What is maximum batch size?
Is it not allowed to control batch size?
Or Can I change only smaller batch size?

**Comment by zakki** [comment]
The limit of maximize batch size depends on vram size.

A lot of  "EVAL QUEUE FULL" means CPU threads are waiting for GPU DCNN evaluation.
Bigger batch size mitigates this more or less.

As far as I tried with 4 core i7-6700K and pascal titan-x, batch size 8 is much throughput than batch size 1 in exchange for a little bad latency.
And batch size 256 is a little more throughput than batch size 64 in exchange for bad latency.
I don't have enough information to say what is best.

**Comment by j8580** [comment]
What is total number of training set?

**Comment by zakki** [comment]
No handicap games from KGS 5d+ & GoGoD 350,000 sgf, 73,000,000 positions.

**Comment by j8580** [comment]
Last question.
Does multi gpu useful to use Ray?
What part does multi gpu effect about?
Speed or strength or both?

**Comment by j8580** [comment]
Plus if I use multi gp

**Comment by zakki** [comment]
There is experimental mpi branch for multi GPUs environment.
Ideally it becomes stronger, but I have not finished it.
#I don't have multi GPU machine.
https://github.com/zakki/Ray/tree/nn-mpi-root

**Comment by j8580** [comment]
Plus if I use multi gpu then Ray use double vram?

**Comment by j8580** [comment]
Sorry for continuous question.
Then Rn3.11.1 doesn't support multiple gpu,right?

**Comment by zakki** [comment]
Yes, you need to merge and compile and debug it to use multiple GPUs.
And it requires VRAM for each GPU (for each MPI processes).
