### ISSUE TITLE
I think it's better to simplify the GTP Shell

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#28]
I like to refer the GTP Shell. But at the present time, reading the contents of Rayon's GTP Shell is somewhat difficult. In my opinion, game board at the GTP Shell is unnecessary and it is degrading readability.

Also, when using the pondering option, there is no need to show the long-line computer thinking.(currently, it shows every data(on average, 20~40lines)  per 1000 counts - like 180000,181000,182000'''. totally hundreds and thousands of long lines per each move)

I think we can simplify and make clear the information of GTP Shell. And it'll enhance the efficiency for user's game analysis.

**Comment by zakki** [comment]
A lot of debug log in UctSearch may have to be suppressed by `--no-debug` option.

BTW, how about Gogui's Analyze Command? I've not finished yet, but it's interesting for game analysis. https://github.com/zakki/Ray/compare/nn...zakki:nn-gogui

**Comment by j8580** [comment]
I agree gtp shell is too difficult.
Gogui is best option I think.

**Comment by zakki** [comment]
Now `--no-debug` works.
