### ISSUE TITLE
SLI error

### ISSUE THREAD

**Issue by zakgod** [zakki/Ray#31]
Single gpu no problem.
But when I use gpu sli I got error.
Can I solve this problem?
I use window 10 .

**Comment by zakgod** [comment]
I use gogui for ray.
In single gpu, no problem.
But when I use two gpu I can't run ray in gogui.

**Comment by zakki** [comment]
It seems that SLI is a technology for graphics processing, and it is not for CUDA/GPGPU.
https://devtalk.nvidia.com/default/topic/451571/cuda-and-sli/

**Comment by zakgod** [comment]
OK not sli.
But still can I use multi gpu for ray?

**Comment by zakgod** [comment]
Any solution for using multi gpu?

**Comment by zakki** [comment]
There is no eaasy way now.

Candidates
- Root parallel: run multiple Rn and sync. https://github.com/zakki/Ray/tree/nn-mpi-root
- Leaf parallel: run worker processes like AlphaGo
- Make CNTK multiple GPU capable in single process.
- Port Rn to multi GPU capable Deep Learning framework.

**Comment by zakgod** [comment]
https://github.com/zakki/Ray/tree/nn-mpi-root
It  works wow.
But I need more test.
I don't know ray's performance increase yet.

**Comment by zakgod** [comment]
Ah  sorry still use only one gpu T t

**Comment by zakki** [comment]
Use mpiexec or mpirun

**Comment by zakgod** [comment]
OK I will try it

**Comment by zakgod** [comment]
I use win10 64bit.
how can I adapt Ray to Gogui with mpiexec?
I used mpiexec -np 2 command in cmd command table. It execute two CNTKs.
and next steps?
Can u explain more details about multi gpu procedure easily?
Really sorry for silly quesion. 
If It needs complicated steps, I will give up. But I will try more.
Just I compiled ur Mpi-root files. and downloaded msmpi.
then...what's next for me to do?

**Comment by zakki** [comment]
I used `mpiexec -n 4 ./ray --thread 8 --reuse-subtree --const-time 20` on Linux to exec 4 ray (each of them use 8 threads).
That branch is very early stage of development, so you need to debug it, and need to implement more.

**Comment by zakgod** [comment]
I have i7 6900k (16threads plus two gpus).
I typed in window cmd command table 'mpiexec -n 4 /ray.exe --thread 16 and so on'.
And at genmove black command, Ray use 16threads and only one gpu. T T
Really sorry bothering you.
What do I do more?

**Comment by zakki** [comment]
I have not completed nn-mpi-root branch.
The priority of parallel implementation is low, since I use single GPU.
Fork and pull request if possible...

**Comment by zakgod** [comment]
ya...I know that you have not completed nn-mpi-root brach.
but just I wanna test it. thx for ur effort.

**Comment by zakki** [comment]
I used MSMPI only for coding, and I ran it on Linux openmpi on EC2, so I don't know well about how to use and what is a right behavior.

**Comment by zakki** [comment]
@zakgod Does this work? https://github.com/zakki/Ray/releases/tag/1.0.15

**Comment by zakgod** [comment]
I can test in next week. Then I will tell u about multi GPU.

**Comment by zakgod** [comment]
You wrote --thread 24 in release . By the way, should I put --thread 24? 
My max thread is 16..still should I put thread 24? or..should I put thread 16?

**Comment by zakki** [comment]
It's example. You can use any number threads.

**Comment by zakgod** [comment]
ok..this weekend..i can test..after test, I will tell u about test results~ thx for ur effort..

**Comment by zakgod** [comment]
There is a little improvement for speed. But too low gpu load to each gpu.
Could you increase for each gpu? Each gpu load is juat 50~60. Rn 4.20 was over 75~. Rn 4.6 was almost over 90~ for gpu load.
About strength I need more test.

**Comment by zakgod** [comment]
Other question..can u brief explain about policy_top_rate_max and search_threshold_policy_rate?

**Comment by zakki** [comment]
Thank you.

There are two situation.
- GPUs are sleeping, because they are fast enough to handle NN from CPU.
- Some lock avoid to run GPUs concurrently.
