### ISSUE TITLE
What do you think If I make Rn's Analysis Mode GUI?

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#33]
Hi, zakki.

I'm enthusiastic for both of computer Go engines and computer programming.

I'm trying to make Rn's Analysis Mode GUI, something like Leela's one.

My goal is to make a rich analysis mode of Rn, which is way better than Leela's.

But I think this structure is too big, so it can't store many nodes on memory.

//  9x9  : 1828bytes
// 13x13 : 3764bytes
// 19x19 : 7988bytes
struct uct_node_t {
  int previous_move1;                 // 1手前の着手
  int previous_move2;                 // 2手前の着手
  std::atomic<int> move_count;
  std::atomic<int> win;
  int width;                          // 探索幅
  int child_num;                      // 子ノードの数
  child_node_t child[UCT_CHILD_MAX];  // 子ノードの情報
  statistic_t statistic[BOARD_MAX];   // 統計情報 
  bool seki[BOARD_MAX];
  bool evaled;
  //std::atomic<double> value;
  std::atomic<int> value_move_count;
  std::atomic<double> value_win;
};

Do you have any idea about reducing this structure's size?

Thank you for reading my article.

ZS

**Comment by zakki** [comment]
It depends on what you need while analysis.
Rn stores thousands of nodes or more.

**Comment by wpstmxhs** [comment]
Thank you for your consideration.

I think I'm able to reduce that size somehow,
But from my estimations, It just saves a little.

By the way, what I'm currently making is this.
It should be useful.

<img src="https://s9.postimg.org/5fivpp8jj/rnanalysis.gif" />

**Comment by ryanzao1105** [comment]
@wpstmxhs may i have your share about your analysis mode of the latest version 4.2.1? 
if yes, email it to me by 184119652@qq.com, thanks very much.

**Comment by ryanzao1105** [comment]
@zakki when could the version 4.2.1 be compiled?

**Comment by zakki** [comment]
I released the 4.2.1 binary.

**Comment by wpstmxhs** [comment]
@ryanzao1105 I have a plan to share it. by forking this project, or by distributing compiled binary.
Currently It's unstable. so I'm working hard to make it stable.
It'll take much time.

**Comment by zakki** [comment]
.
