### ISSUE TITLE
Breaking playout limit

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#36]
As you know, I'm making Analysis Mode GUI of Rn.
In this case, breaking playout limit is important thing.
Because user may want to analyze more than tree size limit.

So I made max heap of nodes sorted by depth,
and made it remove 20000 deepest nodes from memory
whenever nodes are more than tree size - 20000.
(Of course, removed nodes are unlinked from parent nodes before it's removed)

Is it good idea?

**Comment by zakki** [comment]
@koban6 How about this?

**Comment by wpstmxhs** [comment]
I observed that Leela does the same thing.
When I make Leela analyze very long and play some moves, Leela didn't remember statistics of that variation. It means, Leela prunes some variation whenever its memory is full.

**Comment by kobanium** [comment]
I think it can be realized.
However it is not effective for Ray's strength, so I don't have a plan to support it's function soon.
I recommend you to announce to set tree size bigger. It helps a effective analysis mode.
