### ISSUE TITLE
Previous-passed-policy experiment

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#37]
How about this experiment?

Not using only pure policy network as policy, also using policy network output of previous move, but for my turn(enemy passed).
I did this experiment to some other commercial Go engine, by hacking its engine. and made it like more tenukis than before.

It should be fun to try.

**Comment by zakki** [comment]
I'm not sure, but it may be better than current hand craft heuristics. https://github.com/zakki/Ray/blob/nn/src/UctSearch.cpp#L2268

Also more aggressively, filling turns with zero might work.
https://github.com/zakki/Ray/blob/nn/src/GoBoard.cpp#L1960
