### ISSUE TITLE
some command question

### ISSUE THREAD

**Issue by wallwallwall** [zakki/Ray#38]
no-expand command use only nn without MCTS.

but that command don use gpu.

gpu load is 0%.

is it right situation?

**Comment by wpstmxhs** [comment]
If you set no-expand, Rn will only evaluate root's policy network and its child's value networks.

No more GPU calculation will be run. so it's normal.

**Comment by zakki** [comment]
Yes, that's right.

**Comment by zakki** [comment]
`no-expand` is a experimental option for debug.
"No MCTS" means pre-CrazyStone style classical Monte Carlo Go (with neural networks).

If you want to tree-search with only policy and value without MCTS, `Simulation()` call in `UctSearch()` should be disabled.
