### ISSUE TITLE
Displaying good (but not best) sequences in terminal

### ISSUE THREAD

**Issue by pnprog** [zakki/Ray#40]
Hi zakki,

I am the author of [GoReviewPartner](https://lifein19x19.com/forum/viewtopic.php?f=9&t=14050), a tool that uses Go bots to review games. ([code is on github](https://github.com/pnprog/goreviewpartner)) It currently works pretty well using Leela or GnuGo.

I very interested in adding support for Ray (also, it's a recurring request on L19). I had a look recently, using Ray rn-3.11.1, to check what information are available in the terminal for me to parse and extract. The most interesting part is the "**best sequence**", for example:
`Best Sequence : Q4<BLACK : 210/413><28.3493/57>->R16<WHITE : 60/111><6.92834/14>` as on [this screenshot](https://lifein19x19.com/forum/download/file.php?id=8378).

Would it be possible to display in a similar way additional sequences investigated by Ray during MCTS, together with winning % ?

**Comment by zakki** [comment]
It's possible.
Does "during MCTS" means real time? (Top 10 sequences for each 1000 PO, for example)

**Comment by pnprog** [comment]
Dear zakki,
No, I do not mean real time. I just need the few best sequences after the MCTS is completed (when Ray has already made its choice), to be displayed.

**Comment by zakki** [comment]
So, a variant of `PrintBestSequence()` is needed.
https://github.com/zakki/Ray/blob/nn/src/Message.cpp#L384

**Comment by pnprog** [comment]
Hi!
I don't really know about c++, but from what I understand from the code of PrintBestSequence(), maybe it could be modified to get a more general function like PrintOneBestSequence() that displays the best sequence based on it's order.
Maybe it could be done by modifying lines 405~410 as follow:
`upper = 9999999;
for (r = 0; r <= order; r++) {
	max = 0;
	for (i = 0; i < child_num; i++) {
		if (uct_child[i].move_count > max || uct_child[i].move_count < upper) {
			max = uct_child[i].move_count;
			index = i;
		}
	}
	upper = max;
}`

with `order` being one parameter to the function, so that PrintBestSequence() would in fact PrintOneBestSequence() with order=0 as parameter.
But well, I don't really know about c++ in fact.

**Comment by zakki** [comment]
Please try 4.2.5 https://github.com/zakki/Ray/commit/f5dbf50214e222a163d98a73f1eda81e8dd30e79
![image](https://cloud.githubusercontent.com/assets/162515/26521399/a7e6a546-4322-11e7-8e54-4acbe2360ab2.png)

**Comment by roy7** [comment]
GoReviewPartner is a cool tool. Thanks for supporting his efforts @zakki . :)

**Comment by pnprog** [comment]
Dear Zakki,

I just tried 4.2.5 and the **ray-stat** gtp command does exactly the job i need.

Thanks a lot!
