### ISSUE TITLE
where are the "Eval.h"?

### ISSUE THREAD

**Issue by fulowl** [zakki/Ray#41]
when I built "win/ray.sln" in visual studio 2017,it have a problem:
1>..\..\src\UctSearch.cpp(43): fatal error C1083: 无法打开包括文件: “Eval.h”: No such file or directory

how to solve this?

**Comment by zakki** [comment]
It's CNTK's file.

**Comment by fulowl** [comment]
sorry,I still don't kmow what you say. what should I do next?

**Comment by zakki** [comment]
Install CNTK, and set include directories and library dicetroties at VC++ Directories.
https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta12.0

**Comment by fulowl** [comment]
thank u very much!
