### ISSUE TITLE
what is difference between CNTK old version and new version?

### ISSUE THREAD

**Issue by wallwallwall** [zakki/Ray#43]
what is difference?
and.. should i install new version CNTK for RN 4?

and also does new version CNTK influence on old version RN 3....?

**Comment by zakki** [comment]
If you use only binary release, you don't need to install CNTK.

I'm using CNTK 2.0. beta 12.0.
Perhaps newer one should work better, but there are some breaking changes in release notes.
I'm not sure these affect or not.
https://github.com/Microsoft/CNTK/releases
