### ISSUE TITLE
slower than before

### ISSUE THREAD

**Issue by wallwallwall** [zakki/Ray#44]
old version Rn was about 14000 / s playouts

new version Rn is about 9000-10000 /s playouts.

is this right situation? 

furthermore . new version RN has delay and excess time limit many times.

New version Rn has better policy than old version and has also good endgame style  but has so many life and death bugs than before.

many life and death bugs r critical.

what is ur opinion about life and death bugs of new Rn version(Rn 4...)
I tested many times..new version Rn has 10times worse than old version in life and death.
I am not sure the exact result..but i think u changed some life and death policy.

**Comment by zakki** [comment]
V4's model is deeper and slower than V3.
Perhaps current model is optimized for CPU/GPU computing power ratio of my environment i7-6700K and Pascal Titan-X.
V3 ratio may be better when CPU is faster or GPU is slower than mine.
Some auto adjusting system is required, but I don't have good idea.

In many condition, LGR and TGR works well, but sometimes these break endgame.
My tests by self play and cgos, the merits is bit bigger than demerits.

What happen if you disable tgr?
https://github.com/zakki/Ray/blob/nn/src/MoveCache.cpp#L17
`
int tgr1_rate = 0;
`
