### ISSUE TITLE
Please ignore some weird people

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#47]
I really love this project, and appreciate your efforts to make Rn.

btw, I'm planning to contribute my analysis mode GUI of Rn.

Is it okay to do? and how to share my works? Do you have any good idea?

**Comment by extremepsycho** [comment]
I'm sorry zakki. I apologize for trouble in your community. 

But this guy still laughing at me at the DCinside gallery just now.
He pretends polite person in here, but not at the DCinside.(very rude and enjoy annoying people)

He didn't apologized his actions in our community. 
He blamed and stigmatized other capable programmers as liar.
(http://gall.dcinside.com/board/view/?id=baduk&no=269897)

Where there's smoke, there is fire.

contributing? yeah it's very nice and good things and it will help your RN project. that's right.

But thoughtfulness for others is first, I think.

**Comment by wpstmxhs** [comment]
Get out of here and go fuck yourself.

Why do you still continue this things?

**Comment by extremepsycho** [comment]
haha you said that "I enjoy being blamed. Keep blaming me !!"
am I false?

http://gall.dcinside.com/board/view/?id=baduk&no=299121

**Comment by wpstmxhs** [comment]
@zakki

zakkiさんのツイッター見ました。昨日、私が直接GitHubチームに連絡して例のやつのスレやアカウントがすべて消えました。これが真実です。ところで返事してください。私が分析モードを作りましたんですが、私はあまりGitHubの経験ないので具体的にどんな方法で共有するのがいいか分かりません。

P.S: 私は日本語が出来ます。この文章も私が直接書いたんです。機械翻訳ではありません。

**Comment by zakki** [comment]
If you think your analysis mode is useful, please use Fork button and send the Pull Request like #35.
If discussion about design is needed, create a issue for that.
If your analysis mode requires large change (for example, it uses GUI framework like MFC, Win32, Qt), I think it is better to distribute at your site.

**Comment by wpstmxhs** [comment]
Thank you for your reply.
It really helped me. I should try to simplify GUI of Analysis Mode, and also consider compatibility for systems other than Windows.
