### ISSUE TITLE
I wonder it's optimal to evaluate VN like now

### ISSUE THREAD

**Issue by wpstmxhs** [zakki/Ray#48]
Currently, RN evaluates value network by calculating simple average.
But I'm wondering if it's optimal policy.
As you know, deeper node values have less error than shallower ones.
and later values are more accurate than earlier ones (since later reading is more precise).
Hence I suppose you not to calculate simple average, but average with some heuristics.
For example, I think we can try some moving average algorithms and some hand-crafted adjusting heuristics(i.e. emphasizing losing values when winning much).
I want to discuss about this.

**Comment by zakki** [comment]
Not only VN, playouts becomes precise in deep node too.
If there are such adjusting method for MCTS, it may also be useful for APV-MCTS.

**Comment by wpstmxhs** [comment]
Hmm. When older version, I've tried to adjust value network evaluations, and it seemed positive.
I emphasized losing values of mine.

```
double value = 1 - p;// color[j] == S_BLACK ? p : 1 - p;
if(req->color != my_color) value = 1 - value;

if(value < 0.3) value /= 2.0;
else if(value < 0.4) value /= 1.3;
else if(value < 0.45) value /= 1.1;

if(req->color != my_color) value = 1 - value;
```

It doesn't help much when versus Rn itself, but helps a little against humans.
I'm figuring out how to reduce error of VN.
