### ISSUE TITLE
How to run Rn on board 9*9

### ISSUE THREAD

**Issue by DeGuang1996** [zakki/Ray#49]
I can't run Rn on board 9*9, I set the boardsize to 9, but when it genmove b or w,it closed automatically,how can I solve it? Thanks.
![image](https://cloud.githubusercontent.com/assets/23307241/26788697/ade51fca-4a40-11e7-9032-56ee643c6258.png)

**Comment by zakki** [comment]
Both Rn program and NN model are hard coded to 19x19.
https://github.com/zakki/Ray/blob/nn/src/GoBoard.cpp#L1901
https://github.com/zakki/Ray/blob/nn/cntk/ResNetV90a.bs#L28

Maybe NN weights can be reused, because there is no fully-connected layer.

**Comment by DeGuang1996** [comment]
OK,Thank you very much.

**Comment by zakki** [comment]
https://github.com/zakki/Ray/tree/nn-v6
