### ISSUE TITLE
Ray is consistenltly losing every single game to Leela, what is going on?!?!

### ISSUE THREAD

**Issue by davidye2020** [zakki/Ray#55]
https://www.reddit.com/r/baduk/comments/6g0imx/ray_losing_all_games_against_leela/?st=j3p2z0z2&sh=fad146df

**Comment by zakki** [comment]
Could you send command line parameters and sgf with stderr message or console log?

**Comment by davidye2020** [comment]
How do I get these? I didn't log, because the gtp console on the left side of my sabaki board only has a small cache size?

Anyway, I just tested a new game, I gave Ray THREE handicap stones and Leela still beat it!

Something is either wrong with my setup for seriously Leela is a lot stronger than Ray. 

https://pastebin.com/pwbMA0Hq
https://i.imgur.com/ke4zz87.jpg 
https://gokibitz.com/kifu/ryMeouvG-

**Comment by zakki** [comment]
Did you use `--thread <N>`?

**Comment by davidye2020** [comment]
Yes, I use --thread 8 for Rayon and --threads 8 for Leela, both of them have pondering turned off. 

Even when I test on Google platform, I use --thread 24, but no help. Leela always wins. 

On my home PC it is Core i7-4970k Not Overclocked
And a mere GTX 1050Ti Mini

**Comment by davidye2020** [comment]
https://pastebin.com/5jHjZDuM
https://pastebin.com/UF2wAidU

This game I gave Ray 20 Komi points, he still resigned.

**Comment by zakki** [comment]
I use gogui-twogtp to test. I'll try on my environment.

By the way, since Rn can use single GPU, I think single K80 and 2 or 3 CPU cores are used on Google's cloud, and other threads are wait for NN evaluation on GPU.

**Comment by davidye2020** [comment]
So you are saying Rn can only take advantage of one K80 and having more is actually maybe overhead slowing it down? 

I used the Sabaki GUI, I tried GoGui first but it always crashes on me.

**Comment by zakki** [comment]
Yes, multiple GPU support is todo. https://github.com/zakki/Ray/issues/31
As far as I tested on the `rayn` branch, 64-cores EC2 p2.16xlarge is weaker than 4-cores i7-6700K & Pascal Titan-X.

**Comment by davidye2020** [comment]
[Ray_lose_bigly_sgf.txt](https://github.com/zakki/Ray/files/1063116/Ray_lose_bigly_sgf.txt)

**Comment by zakki** [comment]
50 games on i7-6700K & TITAN X Pascal was 48% (±7.1).

Rn: `Rn.4.4.1.exe --thread 4 --reuse-subtree`
Leela: `Leela0100GTP_OpenCL.exe --gtp --threads 4 --noponder`

There are some "EVAL QUEUE FULL" in your log.
Perhaps v4.x is too heavy for most GPU.
How about v3.11?

http://gokifu.net/t2.php?s=71497007103568

**Comment by davidye2020** [comment]
I'm trying with 311 now. 

BTW I always got the EVAL QUEUE FULL even on Google platform.
