### ISSUE TITLE
Use SoftMax policy and cntk files

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#56]
I would like to know release rn.4.2.5  have use SoftMax policy?
What is the use of add cntk files?
It seems that the compiler will not use this file

**Comment by zakki** [comment]
No.
That fix is running on CGOS as Rn.4.4.
It fixes some corner case bug at endgame, but rating seems not to improved.
http://www.yss-aya.com/cgos/19x19/cross/Rn.4.4-4c.html

.cntk, .bs (and obsoluted .ndl and .mel) are used by cntk command to train model.bin.
https://github.com/zakki/Ray/wiki/Train

**Comment by a22063821** [comment]
Thank you for your answer
Meaning is own download and compiler will be 4.4?
Use your compile just to 4.2.5
Right?

**Comment by zakki** [comment]
Yes.
