### ISSUE TITLE
Gogui analysis

### ISSUE THREAD

**Issue by j8580** [zakki/Ray#57]
Can u make gogui analysis mode for 3.11?
I wanna some test.
Rn 3.11 has some bugs and weak end game.
But it has fast speed advantage compared to rn4.25. I want some tests with 3.11 gogui analysis.
Really thx for ur efforts.

**Comment by zakki** [comment]
`git co 7ac44b65bf09f31e1316aafe5abb7692ae51f80d && git revert 7c1c2e6afc018c7ed41709fa9f23efb02cb8e803` seems to work.

**Comment by j8580** [comment]
Thx
