### ISSUE TITLE
about  sgf  files for training

### ISSUE THREAD

**Issue by jiangfan2** [zakki/Ray#58]
HI,zakki
How many  KGS/GoGod/Tygem  sgf files are used for training Policy Network and Value Network? (to generate the model file(Ray-rn-4.2.5\uct_params\model.bin,model2.bin)).
Can these sgf files be shared with us?

**Comment by zakki** [comment]
I used Tygem and GoGoD dataset 1.5M sgf files.
https://lifein19x19.com/forum/viewtopic.php?f=18&t=14169&hilit=dataset

**Comment by jiangfan2** [comment]
Is "TYGEM "9D vs 9D" dataset (1,516,031 games) "data sets?
How about  the size of generate 'data.txt' file？

**Comment by zakki** [comment]
Yes, it is.
data.txt is about 800GB.
