### ISSUE TITLE
Surrender Problem in the beginning phase

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#59]
Hello zakki.

I enjoy handicap game(oki-go) with AI programs.

Leela and Zen support the hendicapped-go mode.

they do not surrender early in the game, even if their winning rate is too low.

But RN surrenders in the beggining part so that I cannot play handicap game with RN.

I think it'll be better to add the option of the timing of surrender to the RN.

For example.. --surrender 150    : Setting the timing of surrender. 150 means 150moves(手)

And then even though winning rate is too low, RN won't surrender before 150 moves.

Or you can also add the option '--surrender-condition 5'  : Setting the condition of surrender. 

In this case, RN never surrender until its winning rate is 5%.

Or you can just make RN do not surrender in the early phase. this is the simplest way without adding option.

RN has potential power and unusual play style that Leela and Zen do not have...

So I really like RN.

I always appreciate and thank you for developing and upgrading RN. 👍

**Comment by zakki** [comment]
Use `ray-param resign_threshold 0.1`
