### ISSUE TITLE
Why CPU_only version so weak?

### ISSUE THREAD

**Issue by bihonglu** [zakki/Ray#6]
Hi zakki, 

I noticed that the CGOS rn-3.9 only has 4 cpu with no GPU.  Rn.3.9-4c ranked only second to Zen. 

In my own testing,  the DGS bot I set up has 1 GPU with 50000 playout,  2 threads in ray command option.  The strength is very strong at 6d ranking now at DGS.  However,  the same playout number in CPU only linux machine yielded a much weaker bot, possibly several stones weaker than the GPU version.  My CPU only set up is as below: 
./ray --no-gpu --thread 2 --playout 50000  

at 2 CPU 4 CPU like below: 
./ray --no-gpu --thread 4 --playout 50000

Both CPU only has 4G memory. 

I would thought the same number of playout should generate same strength regardless of GPU or CPU.  Why is the difference on strength?

Shoreline

**Comment by bihonglu** [comment]
One difference I did notice was that in 1 GPU dual core linux box,  the memory usage was close to 100%, but no swap was used. 

In both 4 CPU  or 2 CPU + 4G memory  CPU_ONLY setting,  it appears that the machine was on swapping on the size of several hundreds MB or up to 1 G.   It looks as if the software requires much more memory trigger memory swapping.  Not sure whether this is one of key reason for the weakness I observed on CPU_only  Rayon strength.

**Comment by zakki** [comment]
A known issue about CNTK before 2_0_Beta_8 is CPU mode doesn't support batch normalization, so value network returned garbage value.
That makes CPU mode rn  weaker than gnugo.

Another problem is that DCNN evaluation on CPU is too slow to reflect tree-search. It was fixed on rn-3.10.2 by waiting DCNN. (That fix strength, but it slow down simulation near 100po/sec as side effect)
https://github.com/zakki/Ray/commit/9fd62f86c4aa9df788776c25db9b72267ec7f199

If both of them doesn't fx a problem, please send stderr log and sgf.

**Comment by bihonglu** [comment]
Thanks for the info.  My Ubuntu CNTK is beta 11, that should be fine.   I have compiled  RN3.10.2 in CPU only mode, and it is running very slowly in games testing. That is good sign and it is supposed to be very slow without GPU.   I will let you know after I finished the strength testing. 

Strong CPU only mode Rayon is still quite usefully for me.  Sometimes I need to offload the DGS Rayon Bot to  virtual machine in CPU only mode in order to free up my main desktop linux machine for other short term testing purposes or software development purpose.

**Comment by zakki** [comment]
> I noticed that the CGOS rn-3.9 only has 4 cpu with no GPU. Rn.3.9-4c ranked only second to Zen.

CGOS rn.*.4c use 4core i7 and GTX-980Ti GPU.
Only Rn.3.3.1-4c0g in BayesElo list runs without GPU. This shows that Rn cannot outperform Ray without GPU in same computation time.

**Comment by bihonglu** [comment]
I think CPU_only issue is lower priority because Rayon is mainly designed for GPU version.  But still I want to report here that re-compiled RN3.10-2  CPU_only is still weak in my testing.  it takes longer time to run, 6 minutes to 8 minutes per move on 50,000 playout, but the end result was that Rayon lost  oakfoambot on 4 stones or 5 stones handicap. As can be seen at DGS,  Rayon Bot on GPU can beat on 4 to 5 stones handicap comfortably.  This could be cntk issue rather than Ray issue.   

Just a tip that I heard from other places,  the caffe version on CPU only does not work on CPU_only for multiple threaded version.  Same thing could be here at cntk.   I tried ./ray --no-gpu --thread 1 --playout 50000    trying to disable  multithread version, but still did not work, it still using 200% or more  CPUs load and the result was still quite weak.

**Comment by zakki** [comment]
I tried 20 games of `Rn.3.10.2.exe --no-gpu --thread 1 --playout 5000` vs `White command: Rn.3.10.2.exe --thread 6 --playout 5000`.
Win rate of CPU only was 40% (±11). I cannot say it is strong or weak.

BTW, asynchronous evaluation may not be efficient in CPU only mode, I think policy_batch_size and value_batch_size should be 1 when `--no-gpu`.

**Comment by bihonglu** [comment]
I noticed that you used window version while I was testing on Ubuntu linux 14.04 version.  This issue may be specific to  Linux platform only.
