### ISSUE TITLE
Can you compile RN4.5?

### ISSUE THREAD

**Issue by keeAI** [zakki/Ray#60]
Hi ,@zakki
I appreciate your RN very much
I want to test RN4.5，Can you compile RN4.5?
Thanks very much

**Comment by zakki** [comment]
I can compile it. Is there any error?

I think 3e7cbdb 's check isn't enough, so sometime it replaces good move with bad move in some condition.

**Comment by keeAI** [comment]
Thank you. I see
I found some of RN4.5's life and death mistakes. Is it because RN4.5 doesn't have enough time to think?

**Comment by zakki** [comment]
Perhaps it's open issue.
Rn needs millions years to solve some kind of life and death.
https://github.com/koban6/Ray/issues/3

**Comment by crayzok** [comment]
after milions years, Rn won't need to find that solution if goal is just beating Kejie haha.
But if zakki's goal is finding the answer of Go(over beating human), it must need millions years right.
