### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by nginx-x** [zakki/Ray#63]
(1) In Linux -
with Ray 4.5 - gcc 4.8.4

root@tt:/usr/local/src/Ray-rn-4.5# make
g++ -O3 -Wall -std=c++11 -std=c++1y   -I/home/ubuntu/src/cntk/Include/ -c src/Gtp.cpp -o src/Gtp.o
src/Gtp.cpp: In function ‘void GTP_ray_best_sequence()’:
src/Gtp.cpp:825:8: warning: unused variable ‘pos’ [-Wunused-variable]
   char pos[10];
        ^
src/Gtp.cpp:827:7: warning: variable ‘point’ set but not used [-Wunused-but-set-variable]
   int point = PASS;
       ^
src/Gtp.cpp: In function ‘void GTP_ray_stat()’:
src/Gtp.cpp:868:8: warning: unused variable ‘pos’ [-Wunused-variable]
   char pos[10];
        ^
src/Gtp.cpp:870:7: warning: variable ‘point’ set but not used [-Wunused-but-set-variable]
   int point = PASS;
       ^
src/Gtp.cpp: In function ‘void DumpSparse(std::ostream&, std::vector<float>)’:
src/Gtp.cpp:964:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < data.size(); i++) {
                                  ^
src/Gtp.cpp: In function ‘void DumpDense(std::ostream&, std::vector<float>)’:
src/Gtp.cpp:974:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i < data.size(); i++) {
                                  ^
src/Gtp.cpp: In function ‘void DumpFeature(const uct_node_t&, int, int, int)’:
src/Gtp.cpp:1008:18: error: ‘make_unique’ was not declared in this scope
     stream_ptr = make_unique<ofstream>("data.txt", std::ios::app | std::ios::binary);
                  ^
src/Gtp.cpp:1008:38: error: expected primary-expression before ‘>’ token
     stream_ptr = make_unique<ofstream>("data.txt", std::ios::app | std::ios::binary);
                                      ^
src/Gtp.cpp:1008:78: warning: left operand of comma operator has no effect [-Wunused-value]
     stream_ptr = make_unique<ofstream>("data.txt", std::ios::app | std::ios::binary);
                                                                              ^
src/Gtp.cpp: In function ‘void GTP_features_store()’:
src/Gtp.cpp:1037:9: warning: unused variable ‘command’ [-Wunused-variable]
   char *command;
         ^
src/Gtp.cpp: In function ‘void GTP_stat_po()’:
src/Gtp.cpp:1204:7: warning: unused variable ‘pos’ [-Wunused-variable]
   int pos = -1;
       ^
src/Gtp.cpp:1205:7: warning: unused variable ‘length’ [-Wunused-variable]
   int length;
       ^
src/Gtp.cpp: At global scope:
src/Gtp.cpp:1061:1: warning: ‘void GTP_stat()’ defined but not used [-Wunused-function]
 GTP_stat(void)
 ^
src/Gtp.cpp:129:14: warning: ‘next_token’ defined but not used [-Wunused-variable]
 static char *next_token;
              ^
src/Gtp.cpp:905:12: warning: ‘features_turn_count’ defined but not used [-Wunused-variable]
 static int features_turn_count = 0;
            ^
src/Gtp.cpp:906:12: warning: ‘features_turn_next’ defined but not used [-Wunused-variable]
 static int features_turn_next = 1;
            ^
make: *** [src/Gtp.o] Error 1

(2) In Visual Studio 2017
It dosen't contain "Eval.h" as mentioned in UctSearch.cpp line 43.

Is there's any solutions for build this whole project properly?
Please let me know if any specific environment/procedure is needed.

**Comment by nikoryu** [comment]
Which Linux distribution are you using? I could compile Ray-rn-4.2.5 on Ubuntu Linux.
Maybe the following discussion on Life in 19x19 could be helpful:
https://lifein19x19.com/viewtopic.php?f=18&t=14265

**Comment by nginx-x** [comment]
Ubuntu 14.04 with both of gcc 5.4 and 4.8 - dosen't work.
Windows attempt - Win 10 with VS2017. so I got CNTK 2.0 and added Eval.h and it throws missing EvalDll.lib error, even after I put that in ./src and ./cntk.

Is there's any proper manual for building this project?

**Comment by nikoryu** [comment]
I suggest you remove "-std=c++11" in Makefile (Line 5) and try to compile again. I got the same compile error when I tried to compile with only C++11 features.
I do not know about Windows installation, but you need CNTK for Ubuntu as well. If you have not already done that, this guide will be helpful:
https://docs.microsoft.com/en-us/cognitive-toolkit/setup-linux-binary-script

I do not think there is a proper manual, which is guaranteed to work in most common settings, available yet. So we need to share our experience.

**Comment by gunlord** [comment]
I got the same compile error on CentOS 7. I tried remove "-std=c++11" in Makefile and the error remains. :(

**Comment by nikoryu** [comment]
Do you know the version of gcc you used? It should be gcc 4.9 or higher as stated in Makefile.
