### ISSUE TITLE
How do increase the number of playouts per second?

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#67]
I want to use the new version, but the playouts is too low per second
How can I modify it?

**Comment by crayzok** [comment]
upgrade your computer :D

**Comment by a22063821** [comment]
I would prefer to port the old version of the high playouts per second to the new version

**Comment by a22063821** [comment]
My gpu use 1060 and a use of 1080 play chess
My cpu is 2600k his cpu is ryzen 1800x
My rn version is old version his rn version is new version
I think it's because I playouts per sec higher than he
I won in the middle plate

My configuration is lower than his
But still can win
On behalf of Code of the impact of relatively large

**Comment by a22063821** [comment]
Zakki 4.6.0 per second playouts improved a lot
I think it is good

**Comment by zakki** [comment]
Now if GPU is bottleneck, the value network isn't evaluated until leaf node is visited some times.
It seems not bad, but I'm not sure it is good enough.
