### ISSUE TITLE
can rn be stonger in linux system?

### ISSUE THREAD

**Issue by ryanzao1105** [zakki/Ray#68]
1) can rn be stonger in linux system?
2) why is the version 4.6.0 tar.gz downloaded every time in size of only 7 MB not as labelled as 46.6y MB?
3) to compile in linux does not need visual c++ studio or something else, just extract the tar.gz file and make ?

**Comment by crayzok** [comment]
you should download rn 4.2.1 too. (https://github.com/zakki/Ray/releases/download/rn-4.2.1/Rn.4.2.1.7z)
and then overwrite 460 files to 421 folder. 
tar file just have existing files that are same with 421's

**Comment by ryanzao1105** [comment]
you  mean to download the RN 4.6.0.7z file and the 4.2.1.7z file , then extract them to the same fold in Linux  and make ?

or the Linux version is just the sanme from 4.2.1 to 4.6.0?

**Comment by zakki** [comment]
1. Which are you comparing with?
2. I don't know why, but your file is broken. Network, GitHub, Browser or something else.
Retry download or use git.
3. Setup g++ and cntk, and modify Makefile. Other issues and lifein19x19 thread may be useful.
https://github.com/zakki/Ray/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20linux
https://lifein19x19.com/viewtopic.php?f=18&t=14265&sid=96274443efd4d1dd655245c544df9681
The binary release in 7z format is for Windows.

**Comment by ryanzao1105** [comment]
1) i meant comparing with the same version in windows 10 system
2) this error happens when i am compiling on the command of "make": 
 " src/UctSearch.cpp:43:18: fatal error: Eval.h: No such file or directory "

**Comment by zakki** [comment]
> i meant comparing with the same version in windows 10 system

Almost same.

> this error happens when i am compiling on the command of "make":

https://github.com/zakki/Ray/issues/68#issuecomment-309974532
