### ISSUE TITLE
What does "Eval queue full" mean?

### ISSUE THREAD

**Issue by GenjiWu** [zakki/Ray#69]
After "Eval queue full" shown in the GTP, Rayon often plays some unexpected move. How to avoid it?
(7700k+1060 6g+8G RAM)
Beside, sometimes Rayon is not very sensitive to life and death. One big part may have been killed but it still gives a high evaluate on the win rate.

**Comment by zakki** [comment]
It means that Policy and Value Network evaluation on GPU is bottleneck, MCTS on CPU is sleeping.
Implementing evaluation on both GPU and CPU may avoid it.

> One big part may have been killed but it still gives a high evaluate on the win rate.

It's common problem of MCTS Go. I think investigation on reinforce learning and BV-ML-VN are needed.

**Comment by GenjiWu** [comment]
Cool, looking forward to Rayon with new algorithms. Thanks 👍 .
