### ISSUE TITLE
Parameter tuning

### ISSUE THREAD

**Issue by zakki** [zakki/Ray#70]
Current parameters are selected for 2.x.
Since 3.x and 4.x evaluate VN at leaf nodes, best parameters may differ.

- EXPAND_THRESHOLD_19
- c_puct
- value_scale

**Comment by wpstmxhs** [comment]
In my experience, VN winrate is more accurate than MC winrate.
I think value_scale should be greater than 0.5.

**Comment by yueyunze** [comment]
Well,As I see.3.x's parameter is thread 8 and 4.x's parameter is thread 4.Well,3.x's endgame is too bad.So I suggest using 4.x.To improve the endgame,the endgame's value can be changed to 0.6,so it will perform better on endgame.A little higher VN value is also more effective when playing "--superko".

**Comment by zakki** [comment]
Now we can modify parameters via GTP.
https://github.com/zakki/Ray/releases/tag/rn-4.6.1

**Comment by zakki** [comment]
https://github.com/zakki/rn-tools/tree/master/clop
