### ISSUE TITLE
What's the difference between Rn.4.6-4c and Rn.4.6-8c1g?

### ISSUE THREAD

**Issue by keeAI** [zakki/Ray#74]
Now，Rn.4.6-8c1g's  BayesElo 3730，Rn.4.6-4c's BayesElo 3558
Why? Just because of the different computer hardware?

**Comment by zakki** [comment]
I heard it uses 7 threads on E5-2679 V4 and 1080ti FE.
Perhaps just because of hardware, but I don't have detail log.

**Comment by wpstmxhs** [comment]
It seems ray's strength is depending on its running computer hardware pretty much.
More likely, on graphic card(GPU) performance.
shann99(sorryz)'s graphic card is nVidia GeForce GTX1080Ti.
(shann99 is who runs 8c1g on CGOS)

Also, It seems program settings are important too.
