### ISSUE TITLE
I run ray  throwing an error! help me

### ISSUE THREAD

**Issue by leesng** [zakki/Ray#8]
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# ./ray 
Init CNTK
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  no closing " found in parameters
已放弃 (核心已转储)
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray#

**Comment by zakki** [comment]
Do you use linux?
Maybe a parameter of CreateNetwork() is something wrong.
Please edit `src/UctSearch.cpp`  like below, and let me know.
```
cerr << "CreateNetwork('" << networkConfiguration << "')" << endl;
nn_model->CreateNetwork(networkConfiguration);
```

**Comment by leesng** [comment]
yes, i  use ubuntu16.4,

cntk ver :  CNTK for Linux v.2.0 Beta 12 GPU with 1bit-SGD
install-cmd : ./install-cntk.sh --py-version 35

I have added printing-code and the log is here:

(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# ./ray
Init CNTK
CreateNetwork('modelPath="./uct_params/model.bin"')
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  no closing " found in parameters
已放弃 (核心已转储)
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray#

**Comment by zakki** [comment]
Thank you, it seems no problem.

@bihonglu Do you know something about this?

**Comment by bihonglu** [comment]
Don't know anything about this.  But the way, when I did Ubuntu 14.04, I did not use 1bit-SGD. 
I forgot what it is, but it was not suitable for my situation.

**Comment by leesng** [comment]
i use  cntk without 1bit-sgd, the log is this:

(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# ./ray
Init CNTK
CreateNetwork('modelPath="./uct_params/model.bin"')
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  configparameters: required parameter missing: unknown:modelPath
已放弃 (核心已转储)
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# 


if i use cmd :/root/Ray/ray, then log:
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# /root/Ray/ray 
Init CNTK
CreateNetwork('modelPath="/root/Ray/uct_params/model.bin"')
terminate called after throwing an instance of 'Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>'
  what():  unmatched bracket found in parameters
已放弃 (核心已转储)
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray#

**Comment by zakki** [comment]
Is it CNTK configuration problem?

"I can build my application using EvalDll.lib/dll, but got the exception like below when running"
https://github.com/Microsoft/CNTK/wiki/Troubleshoot-CNTK

**Comment by leesng** [comment]
yeah,i use g++-4.8, it works.thx.

But,the first time,it is ok;  then it simply exits after that：

(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# ./ray 
Init CNTK
CreateNetwork('modelPath="./uct_params/model.bin"')
ok
(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray#

**Comment by zakki** [comment]
Some time ray exits, other time ray works on linux.
Maybe there are some bugs something like memory corruption or race condition.

**Comment by leesng** [comment]
why the 1st move is : move 1 to  **# move 7** ?


(/root/anaconda3/envs/cntk-py35) root@leenux:~/Ray# ./ray 
Init CNTK
ok
clear_board
= 

showboard
Prisoner(Black) : 0
Prisoner(White) : 0
Move : 1
     A B C D E F G H J K L M N O P Q R S T
   +---------------------------------------+
19:| + + + + + + + + + + + + + + + + + + + |
18:| + + + + + + + + + + + + + + + + + + + |
17:| + + + + + + + + + + + + + + + + + + + |
16:| + + + + + + + + + + + + + + + + + + + |
15:| + + + + + + + + + + + + + + + + + + + |
14:| + + + + + + + + + + + + + + + + + + + |
13:| + + + + + + + + + + + + + + + + + + + |
12:| + + + + + + + + + + + + + + + + + + + |
11:| + + + + + + + + + + + + + + + + + + + |
10:| + + + + + + + + + + + + + + + + + + + |
 9:| + + + + + + + + + + + + + + + + + + + |
 8:| + + + + + + + + + + + + + + + + + + + |
 7:| + + + + + + + + + + + + + + + + + + + |
 6:| + + + + + + + + + + + + + + + + + + + |
 5:| + + + + + + + + + + + + + + + + + + + |
 4:| + + + + + + + + + + + + + + + + + + + |
 3:| + + + + + + + + + + + + + + + + + + + |
 2:| + + + + + + + + + + + + + + + + + + + |
 1:| + + + + + + + + + + + + + + + + + + + |
   +---------------------------------------+
= 

genmove black^[[D^[[D^[[D^[[D
Time Limit    : 10 Sec
Playout Limit : 100000000 PO
      A   B   C   D   E   F   G   H   J   K   L   M   N   O   P   Q   R   S   T
   +----------------------------------------------------------------------------+
19:| 51  51  51  51  50  50  50  50  49  49  50  51  51  51  50  51  51  51  50 |
18:| 51  51  51  51  51  50  50  50  49  49  49  51  51  51  50  51  51  50  50 |
17:| 51  52  51  51  50  50  50  48  49  49  49  50  51  52  51  52  51  51  50 |
16:| 51  50  50  51  50  49  50  49  48  49  49  50  51  52  52  54  52  51  50 |
15:| 50  51  50  50  49  50  50  50  48  48  49  48  50  50  50  53  52  49  49 |
14:| 50  51  50  49  50  50  49  49  49  49  49  48  49  50  51  50  49  49  49 |
13:| 51  51  51  49  50  50  51  51  50  49  48  49  49  50  50  49  49  49  48 |
12:| 51  51  51  50  50  50  49  50  49  50  50  50  50  52  51  49  49  49  49 |
11:| 50  50  51  50  49  49  49  50  49  50  49  50  51  49  49  50  49  50  49 |
10:| 50  51  51  48  48  49  48  49  49  49  50  51  50  50  50  52  50  49  49 |
 9:| 49  49  50  49  48  50  49  50  50  50  51  49  50  50  51  51  50  49  49 |
 8:| 49  50  51  51  51  49  50  49  50  49  49  48  49  50  51  50  51  50  50 |
 7:| 50  51  51  51  51  50  49  49  48  50  49  49  50  50  50  50  51  51  51 |
 6:| 50  51  54  54  53  49  50  48  50  50  49  50  50  50  50  51  51  51  52 |
 5:| 51  52  54  55  53  51  50  50  50  50  49  49  49  49  50  50  52  52  51 |
 4:| 53  53  55  57  55  53  52  51  51  50  50  50  49  49  50  50  52  52  51 |
 3:| 54  54  54  56  56  54  52  50  51  49  49  49  50  49  50  51  49  51  51 |
 2:| 54  54  54  55  53  52  52  51  50  51  50  49  49  50  49  50  50  50  50 |
 1:| 54  54  54  54  53  52  52  51  51  51  50  49  49  50  50  50  50  50  50 |
   +----------------------------------------------------------------------------+
BLACK+142.5
Best Sequence : D4(BLACK : 440/871)<62.0328/125>->Q4(WHITE : 194/353)<25.0919/50>->D16(BLACK : 41/96)<6.39322/13>->Q16(WHITE : 50/87)<9.11772/18>->R4(BLACK : 48/110)<6.37803/13>->R3(WHITE : 33/59)<2.92773/6>
Prisoner(Black) : 0
Prisoner(White) : 0
Move : 7
     A B C D E F G H J K L M N O P Q R S T
   +---------------------------------------+
19:| + + + + + + + + + + + + + + + + + + + |
18:| + + + + + + + + + + + + + + + + + + + |
17:| + + + + + + + + + + + + + + + + + + + |
16:| + + + B + + + + + + + + + + + W + + + |
15:| + + + + + + + + + + + + + + + + + + + |
14:| + + + + + + + + + + + + + + + + + + + |
13:| + + + + + + + + + + + + + + + + + + + |
12:| + + + + + + + + + + + + + + + + + + + |
11:| + + + + + + + + + + + + + + + + + + + |
10:| + + + + + + + + + + + + + + + + + + + |
 9:| + + + + + + + + + + + + + + + + + + + |
 8:| + + + + + + + + + + + + + + + + + + + |
 7:| + + + + + + + + + + + + + + + + + + + |
 6:| + + + + + + + + + + + + + + + + + + + |
 5:| + + + + + + + + + + + + + + + + + + + |
 4:| + + + B + + + + + + + + + + + W B + + |
 3:| + + + + + + + + + + + + + + + + W + + |
 2:| + + + + + + + + + + + + + + + + + + + |
 1:| + + + + + + + + + + + + + + + + + + + |
   +---------------------------------------+
All Playouts       :     3134
Pre Simulated      :        0
Win                :     1542
Thinking Time      :  10.0189 sec
Winning Percentage :  49.2023%
Value              :  50.1017%  448
Winning Percentage2:  49.2623%
All Value          :      448
Playout Speed      :      312 PO/sec 
Eval NN Policy     :      208
Eval NN Value      :      477
Eval NN            :      192/448
Count Captured     :        0
Score              :     -7.5
= D4

**Comment by zakki** [comment]
That is `Best Sequence : D4(BLACK : 440/871)<62.0328/125>->Q4(WHITE : 194/353)<25.0919/50>->D16(BLACK : 41/96)<6.39322/13>->Q16(WHITE : 50/87)<9.11772/18>->R4(BLACK : 48/110)<6.37803/13>->R3(WHITE : 33/59)<2.92773/6>`

**Comment by zakki** [comment]
`fgets` in `GTP_main()` sometimes returns NULL.
A patch below fix, but I'm not sure it is legal or not.

```
-  while (fgets(input, sizeof(input), stdin) != NULL) {
+  //  while (fgets(input, sizeof(input), stdin) != NULL) {
+  while (true) {
+    if (fgets(input, sizeof(input), stdin) == NULL)
+      continue;
```

**Comment by leesng** [comment]
yes, i have fixed the bug, and there are my  pacths:

[0002-Fix-the-fgest-return-null-bug-some-times.patch.txt](https://github.com/zakki/Ray/files/818503/0002-Fix-the-fgest-return-null-bug-some-times.patch.txt)
[0001-Change-Makefle-to-compile-RayGo-using-CNTK-libs-in-u.patch.txt](https://github.com/zakki/Ray/files/818504/0001-Change-Makefle-to-compile-RayGo-using-CNTK-libs-in-u.patch.txt)

**Comment by leesng** [comment]
i think it is need clean the stdin buffer，before fgets

**Comment by zakki** [comment]
Fixed 0002

**Comment by ghost** [comment]
The error is due to ABI changes. The binaries of CNTK provided by Microsoft appear to be compiled with gcc-4.8. With 5.1 I think they changed the ABI. You can still use the old ABI with compiler argument `-D _GLIBCXX_USE_CXX11_ABI=0`.
