### ISSUE TITLE
model3.bin

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#81]
no found model3.bin why?

**Comment by a22063821** [comment]
Nothing I found it

**Comment by zakki** [comment]
I forgot, I'll commit it later. Please use model3.bin in binary release, if you need as soon as possible.

https://github.com/zakki/Ray/releases/download/rn-4.9.1/Rn.4.9.1-diff.7z

**Comment by wpstmxhs** [comment]
Oh, new version!

It seems model3.bin is ensemble of model.bin and model2.bin. Is it right?
(Its file size is approximately model.bin + model2.bin)

I was surprised when Rn 4.9 beated Zen's latest version.
It seems clear that the key point of strength is playout,
as Zen developer Hideki Kato said before.

**Comment by wpstmxhs** [comment]
I also trying to make playouts accurate.
From observation of some tests, It seems good to restrict random simulation moves to rate >= maxrate / 5.
It makes playouts more accurate.

**Comment by a22063821** [comment]
@zakki  ok thanks
