### ISSUE TITLE
cgos window10 connect?

### ISSUE THREAD

**Issue by zakgod** [zakki/Ray#82]
I can connect and execute  leela  in  cgos go server in window10 by window32bit client.

But by windowclinet  Ray always crash..

I think ray use 64 bit. but cgos window client is 32bit.

Is there window 64bit client for Cgos?

or Is there method to execute ray in CGos in window10 environment? I cant use linux client.

**Comment by zakki** [comment]
I'm using patched cgosGtp.tcl
```
proc  eCmd { ch msg } {
    global  progpid

    log  "C->E $msg"
    puts $ch $msg
    gets $ch r1
    if { $r1 == "" } {
        log "skip. Empty line."
        gets $ch r1
        log "--> $r1"
	}
    gets $ch r2

    log "E->C $r1"
```
