### ISSUE TITLE
4.9.1 Amazing...

### ISSUE THREAD

**Issue by crayzok** [zakki/Ray#83]
I set a fight between Leela0.10.0 and RN4.9.1 for 5 games.

And Result was all of Rn4.9.1's win.

I gave about 20 sec to each program.

The winning rate of Leela continues to increase up to 75% but suddenly drop sharply to 50%.

Eventually, Leela resigns.

It seems Rn is able to see something(maybe broader view) that Leela cannot see.

**Comment by GenjiWu** [comment]
Why I receive screens of "Eval queue full" using 4.9.1 ?

**Comment by zakki** [comment]
Rn 4.9's enhancement may depend on deeper (and slower) value network, but not gnugo's safety.
I'm running test, but I'm not sure.
