### ISSUE TITLE
Has RN4.9.1 reached professional level yet?

### ISSUE THREAD

**Issue by keeAI** [zakki/Ray#84]
It feels quite powerful, although there are still some bugs.

**Comment by zakki** [comment]
Yamashita author of Aya estimates that the diffence of gorating and CGOS rating in about 760. http://524.teacup.com/yss/bbs?page=5&
If so, Rn.4.9-4c is 2842 and Rn.4.9-s-8c is 2927. This means 4.9-s-8c reached average professional.
I think Rn may be superior than Ke Jie in some narrow aspect, but Rn is inferior than 10k amateur in other aspect.
