### ISSUE TITLE
goguiで止まる

### ISSUE THREAD

**Issue by igofun** [zakki/Ray#85]
goguiで動かしてるんですが最新のバージョン4.9.1だけ80手超えたあたりで止まってしまします。
その後、再起動して棋譜読み込ませればそれ以降も打てますが原因わかりますでしょうか？
2回とも止まったので不具合かと思います。
windows10x64で動かしてます。

**Comment by zakki** [comment]
ログと起動オプションあれば何かわかるかもしれません
Send the log in gogui shell, and command line arguments.

**Comment by igofun** [comment]
また現象が出たときにログ取ってみます
オプションは、--playout 2000000 --time 18000 --const-time 10 --thread 8 --tree-size 65536 --komi 6.5
です

**Comment by zakki** [comment]
4.9のgnugo連携部分が置き碁に対応できてないようです
Rn 4.9.1's gnugo integration part crashes by handicap games.

**Comment by zakki** [comment]
0b56c05 で修正しました

**Comment by igofun** [comment]
置き碁の問題かわかりませんがログを取れたので見てみたところEVAL QUEUE FULLと出てました。
固まるのはEVAL QUEUE FULLがずっと続いてる状態です。
確認お願いします。
できればこちらが現象が出ないのを確認できるまでクローズにしないでください。

**Comment by zakki** [comment]
4.7以降で--reuse-subtreeをつけていない場合に固まるかもしれません。
検証と修正しますが、とりあえず--reuse-subtreeを試してみてください。

**Comment by igofun** [comment]
それつけて試してみます。
結果を後日またご報告いたします。

**Comment by igofun** [comment]
--reuse-subtreeを付ければ問題ないようです。
以上、よろしくお願いします。
