### ISSUE TITLE
Some questions about 4.9.1

### ISSUE THREAD

**Issue by GenjiWu** [zakki/Ray#86]
1.Rn 4.9.1 is completely unable to work on my computer. I got full screens of "Eval queue full" outputs. And finally it only considers less than 10000 playouts. (7700k,1060 6g,win10 64, 4.6.0 works well)
2.What does Rn.4.9-4c or Rn.4.9-s-8c mean?
3.I installed CNTK libriary but still can't compile it... How to set the Visual Studio to include the CNTK?

**Comment by zakki** [comment]
1. Rn 4.9's DCNN is deeper and slower. I think 10000 PO/sec is fast enough on 4core. https://github.com/zakki/Ray/issues/83
2. Rn.4.9-4c means 4 cores. In detail `--no-early-pass --reuse-subtree --thread 6' on i7-2600K and GTX 980 Ti. I don't run Rn.4.9-s-8c.
3. Setup include path and library path.

**Comment by GenjiWu** [comment]
I don't mean it's slow... It just not works. 
![image](https://user-images.githubusercontent.com/29604043/28237623-1d922ce2-6976-11e7-9009-edb97f75044d.png)
This is the GTP . And finally ->no 10000po/s but 10000po/move
![image](https://user-images.githubusercontent.com/29604043/28237626-3ec1a46a-6976-11e7-8eb4-1740166c2e28.png)
I'm sure this is a bug.

**Comment by zakki** [comment]
Why do you think so? And how can I fix that?

**Comment by GenjiWu** [comment]
It works well if i use 4.6.0. PO/s is about 6500, for every move it's 140000. And there is no "Eval queue full".

**Comment by zakki** [comment]
Rn 4.9 does more task on CPU (gnugo pattern matching, owl life and deth), and more task on GPU (more input, deeper layer. So if 4.9 was as fast as 4.6, that is bug.
