### ISSUE TITLE
Cgos ends a game and automatically reloads rn

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#88]
Is there any way to do that?
After a game is over
Reload attach program rn
Let the memory re-release
Use the --reuse-subtree --tree-size directive
Will consume a lot of memory
If you do not release it is easy to lose the game

**Comment by zakki** [comment]
The python client has `NumberOfGames` parameter.
 http://cgos.sourceforge.net/client-python/doc/index.html

I haven't tried it, but it seems good.

**Comment by a22063821** [comment]
Ok i try it
