### ISSUE TITLE
"EVAL QUEUE FULL " error

### ISSUE THREAD

**Issue by ghost** [zakki/Ray#9]
hi:
 i use 3.10.2.7 " EVAL QUEUE FULL" error occurred ,compute very slowly.why ? please help me.
thank you!
 
GTP command info:

--thread 4 --playout 15000 --no-debug
list_commands
Init CNTK
ok
=
boardsize
clear_board
name
protocol_version
genmove
play
known_command
list_commands
quit
komi
get_komi
final_score
time_settings
time_left
version
genmove_black
genmove_white
black
white
showboard
final_status_list
fixed_handicap
place_free_handicap
set_free_handicap
kgs-genmove_cleanup
features_planes_file
_clear
_store
_dump
_stat

boardsize 19

=

komi 6.5
=

clear_board
=

play b Q16
=

genmove w
EVAL QUEUE FULL
EVAL QUEUE FULL
--playout 15000 --no-debug
name
Init CNTK
ok
= Rayon

version
= 8.0.1

list_commands
=
boardsize
clear_board
name
protocol_version
genmove
play
known_command
list_commands
quit
komi
get_komi
final_score
time_settings
time_left
version
genmove_black
genmove_white
black
white
showboard
final_status_list
fixed_handicap
place_free_handicap
set_free_handicap
kgs-genmove_cleanup
features_planes_file
_clear
_store
_dump
_stat

--playout 15000 --no-debug
list_commands
Init CNTK
ok
=
boardsize
clear_board
name
protocol_version
genmove
play
known_command
list_commands
quit
komi
get_komi
final_score
time_settings
time_left
version
genmove_black
genmove_white
black
white
showboard
final_status_list
fixed_handicap
place_free_handicap
set_free_handicap
kgs-genmove_cleanup
features_planes_file
_clear
_store
_dump
_stat

boardsize 19

=

komi 6.5
=

clear_board
=

play b Q16
=

genmove w
EVAL QUEUE FULL
EVAL QUEUE FULL
EVAL QUEUE FULL
10000.D17: move   412 policy    10.6269 DP:   46.6019 DV:   49.9905 =>    48.2962 0.499196 V:0.499905 LM:0.5  P:0.482962 UCB:0.508693
10000.O17: move    12 policy   0.281536 DP:   33.3333 DV:   48.7059 =>    41.0196 0.499196 V:0.487059 LM:0.5  P:0.410196 UCB:0.487119
10000.C16: move   445 policy   0.834121 DP:   51.6854 DV:   49.5561 =>    50.6208 0.499196 V:0.495561 LM:0.5  P:0.506208 UCB:0.50845
10000.D16: move  2192 policy    19.7469 DP:   50.3193 DV:    49.722 =>    50.0207 0.499196 V:0.49722 LM:0.5  P:0.500207 UCB:0.509211
10000.R14: move    19 policy   0.244599 DP:   42.1053 DV:   49.5788 =>     45.842 0.499196 V:0.495788 LM:0.5  P:0.45842 UCB:0.50842
10000.R11: move    62 policy  0.0012854  P:0.491534 UCB:0.507407
10000. R5: move    55 policy    1.08102 DP:   49.0909 DV:   48.1236 =>    48.6073 0.499196 V:0.481236 LM:0.5  P:0.486073 UCB:0.505376
10000. C4: move   180 policy    1.35077 DP:   50.5556 DV:   49.5288 =>    50.0422 0.499196 V:0.495288 LM:0.5  P:0.500422 UCB:0.507885
10000. D4: move  3853 policy     31.734 DP:   50.0389 DV:   50.0982 =>    50.0686 0.499196 V:0.500982 LM:0.5  P:0.500686 UCB:0.50892
10000. Q4: move  2401 policy    18.2844 DP:   50.3957 DV:   49.8713 =>    50.1335 0.499196 V:0.498713 LM:0.5  P:0.501335 UCB:0.508947
10000. R4: move   193 policy      7.638 DP:   43.5233 DV:   50.1549 =>    46.8391 0.499196 V:0.501549 LM:0.5  P:0.468391 UCB:0.507762
10000. D3: move    81 policy    1.37161 DP:   49.3827 DV:   48.6334 =>    49.0081 0.499196 V:0.486334 LM:0.5  P:0.490081 UCB:0.506808
10000. Q3: move    95 policy   0.571203 DP:   48.4211 DV:   50.9184 =>    49.6697 0.499196 V:0.509184 LM:0.5  P:0.496697 UCB:0.507114
EVAL QUEUE FULL
EVAL QUEUE FULL
Eval NN Policy     :      933
Eval NN Value      :     2501
Eval NN            :      896/2496
Count Captured     :        0
Score              :     -4.5
= Q4

**Comment by ghost** [comment]
restart ok

**Comment by zakki** [comment]
It is debug info notifying that  MCTS search threads is blocked because DCNN evaluation thread is slower.
Perhaps your GPU is slower than CPU.
