### ISSUE TITLE
I have a few question about Rn program's calculation.

### ISSUE THREAD

**Issue by ghost** [zakki/Ray#92]
1. What is the calculation method of Rn program's running?
 : single precision compute(FP32)? Int8? or others?
 
2. What is the calculation method of Rn program's model training?
 
3. What is the best performance GPU or GPGPU in single use when Rn program's running or training?
 : tesla v100? tesla p100? full chip titan Xp? xeon pi?

4. When you run model training, do you use multiple GPU or cloud service?

Anybody knows?

**Comment by zakki** [comment]
1. Rn uses CNTK's FP32 interface.
2. Config files https://github.com/zakki/Ray/tree/nn/cntk  and utilities https://github.com/zakki/rn-tools
3. I don't have Tesla.
4. CNTK can use multiple GPU and multiple PC in training time with MPI.

**Comment by shann99** [comment]
Thanks for your kind answers :)

**Comment by ghost** [comment]
HI. zakki.
 
I'm sorry that I am not understanding about "authored the thread" and "mute the thread"
 
Do do mean that I erase my comment? How can I mute the thread?
 
 
Best Regards,
shann99
 
------------------------------------------
Rn uses CNTK's FP32 interface.Config files https://github.com/zakki/Ray/tree/nn/cntk  and utilities https://github.com/zakki/rn-toolsI don't have Tesla.CNTK can use multiple GPU and multiple PC in training time with MPI.

**Comment by zakki** [comment]
It's help message from GitHub.

**Comment by shann99** [comment]
test
