### ISSUE TITLE
Rn.4.14 looks pretty good

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#93]
Rn.4.14 is currently doing well in cgos

**Comment by zakki** [comment]
It's exp-gnugo-value branch with optimized parameters by CLOP.
https://github.com/zakki/Ray/tree/exp-gnugo-value

```
ray-param policy_temperature 0.68
ray-param c_puct 1.7
ray-param value_scale 0.8
ray-param expand_threshold 15
```

Known issue.
- Escape from captured ladder.

**Comment by a22063821** [comment]
win Zen-14.8-1c1g-2 
Rn take off
Although only one game
Can win a game
It can win the second field too

**Comment by a22063821** [comment]
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2017/07/22/256978.sgf
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2017/07/22/256983.sgf
2 games are not more than 200 hands
Try other things?
Many games are more than 200 hands

**Comment by weaponsjtu** [comment]
How to compile code for running Rn.4.14 ? Thanks.

**Comment by zakki** [comment]
PR about build script is needed to build gnugo components on Linux.

**Comment by weaponsjtu** [comment]
It is difficult to compile successfully. Could you help to provide the build script?
