### ISSUE TITLE
In the function UctSearch(),  I donnot know why Ray.exe only undate the current-node

### ISSUE THREAD

**Issue by leesng** [zakki/Ray#95]
In the function UctSearch(),  I donnot know why Ray.exe only updates the current-node:

 **// 探索結果の反映
  UpdateResult(&uct_child[next_index], result, current);**

But int the UCT search algorithm, it is needed that  use the result of the playout to update information in the nodes on the path from Current-node to Root-node.

**Comment by zakki** [comment]
UctSearch() is called recursively.
