### ISSUE TITLE
Rn put a good advantage completely ruined

### ISSUE THREAD

**Issue by a22063821** [zakki/Ray#98]
(;CA[big5]SZ[19]AP[MultiGo:4.4.4]DT[2017- 7-25-10-51-35]KM[6.5]MULTIGOGM[1]
;B[pd];W[dp];B[qp];W[dd];B[fq];W[dn];B[lq];W[iq];B[io];W[jo];B[jp];W[ip];B[ho];W[jr]
;B[kp];W[gp];B[jn];W[cq];B[pj];W[op];B[pn];W[on];B[om];W[qq];B[rq];W[rp];B[pq];W[qo]
;B[qr];W[pp];B[qq];W[po];B[nn];W[no];B[qm];W[mn];B[nm];W[rm];B[rl];W[or];B[mr];W[ql]
;B[rk];W[oq];B[ro];W[rn];B[sp];W[mm];B[mo];W[lo];B[mp];W[pl];B[pm];W[nl];B[oo];W[qj]
;B[ol];W[qk];B[rj];W[qi];B[ri];W[ok];B[np];W[qh];B[rh];W[qg];B[nk];W[nj];B[ml];W[nd]
;B[mj];W[qc];B[cf];W[ch];B[fc];W[fd];B[gd];W[fe];B[dc];W[cc];B[ec];W[cd];B[jc];W[ge]
;B[hd];W[eh];B[cj];W[cl];B[bh];W[bi];B[ci];W[bg];B[dh];W[cg];B[dg];W[di];B[bf];W[ah]
;B[eg];W[dj];B[fh];W[df];B[ei];W[dk];B[af];W[ag];B[hp];W[gq];B[hq];W[hr];B[go];W[fp]
;B[fo];W[gk];B[ep];W[gr];B[eo];W[eq];B[do];W[co];B[de];W[ef];B[ee];W[ff];B[ed];W[ce]
;B[he];W[hf];B[qd];W[rg];B[pc];W[qn];B[if];W[hg];B[fg];W[gf];B[er];W[fr];B[cp];W[bp]
;B[ai];W[aj];B[dq];W[dr];B[sh];W[sl];B[hi];W[ig];B[jg];W[ii];B[ih];W[jf];B[hh];W[ie]
;B[gg];W[if];B[kf];W[kg];B[jh];W[ke];B[lf];W[le];B[me];W[mf];B[lg];W[mg];B[lh];W[md]
;B[id];W[je];B[fk];W[fl];B[ek];W[el];B[dm];W[en];B[dl];W[ck];B[ne];W[oe];B[og];W[nf]
;B[sm];W[sn];B[cn];W[em];B[bo];W[cp];B[gl];W[fj];B[hk];W[ej];B[cb];W[bb];B[bc];W[db]
;B[ca];W[da];B[bd];W[ba];B[cb];W[ca];B[be];W[cb];B[ab];W[gc];B[gb];W[fb];B[hc];W[eb]
;B[gc];W[ad];B[fa];W[ac];B[mb];W[nb];B[ob];W[kb];B[kc];W[lb];B[nc];W[lc];B[ib];W[jb])

Rn is black

Rn from 137 hands begin crazy 

After the game is over
I go back to the white 136 hand to re-see where the Rn will be
The result is normal location is not going crazy

Why does this happen?

**Comment by zakki** [comment]
When Rn find losing future, it tends to play such moves. 

One possible explanation is that Rn noticed 5 black stones in right side is in danger, so to let it far away search tree, Rn plays atari moves.

With such moves, life and death goes to leaf of search tree.
In simulation, it wins some game, and loses other games.

In contrast, Rn can play better in search tree, so it always loses.

**Comment by zakki** [comment]
See also https://en.wikipedia.org/wiki/Horizon_effect

**Comment by a22063821** [comment]
with zen7 in Mlily lily dream cup appears the same bug

**Comment by zakki** [comment]
This won't fix, until someone (or me) find breakthrough.
